---2017-5-25 14:7:0【E:\develop\workspaces\develop1.9.1\func\pgdb.js:107
			\
			^
SyntaxError: Invalid or unexpected token
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Job.job (E:\develop\workspaces\develop1.9.1\apimain.js:270:20)】
---2017-5-25 14:7:30【E:\develop\workspaces\develop1.9.1\func\pgdb.js:107
			\
			^
SyntaxError: Invalid or unexpected token
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Job.job (E:\develop\workspaces\develop1.9.1\apimain.js:270:20)】
---2017-5-25 14:8:0【E:\develop\workspaces\develop1.9.1\func\pgdb.js:107
			\
			^
SyntaxError: Invalid or unexpected token
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Job.job (E:\develop\workspaces\develop1.9.1\apimain.js:270:20)】
---2017-5-25 14:44:44【TypeError: Converting circular structure to JSON
    at Object.stringify (native)
    at stringify (E:\develop\workspaces\develop1.9.1\node_modules\express\lib\response.js:1070:12)
    at ServerResponse.json (E:\develop\workspaces\develop1.9.1\node_modules\express\lib\response.js:249:14)
    at ServerResponse.send (E:\develop\workspaces\develop1.9.1\node_modules\express\lib\response.js:158:21)
    at E:\develop\workspaces\develop1.9.1\ajax\ajax.js:97:20
    at E:\develop\workspaces\develop1.9.1\node_modules\async\dist\async.js:460:16
    at nextTask (E:\develop\workspaces\develop1.9.1\node_modules\async\dist\async.js:5197:29)
    at E:\develop\workspaces\develop1.9.1\node_modules\async\dist\async.js:5204:13
    at apply (E:\develop\workspaces\develop1.9.1\node_modules\async\dist\async.js:21:25)
    at E:\develop\workspaces\develop1.9.1\node_modules\async\dist\async.js:56:12】
---2017-5-25 15:4:16【TypeError: ..\src\Image.cc:422 Invalid arguments
    at TypeError (native)
    at WrappedImage.encode (E:\develop\workspaces\develop1.9.1\node_modules\_images@3.0.0@images\index.js:81:29)
    at WrappedImage.<anonymous> (E:\develop\workspaces\develop1.9.1\node_modules\_images@3.0.0@images\index.js:142:34)
    at WrappedImage.save (E:\develop\workspaces\develop1.9.1\node_modules\_images@3.0.0@images\index.js:88:37)
    at WrappedImage.save (E:\develop\workspaces\develop1.9.1\node_modules\_images@3.0.0@images\index.js:142:34)
    at E:\develop\workspaces\develop1.9.1\apimain.js:343:34
    at FSReqWrap.oncomplete (fs.js:123:15)】
---2017-5-25 15:6:16【TypeError: ..\src\Image.cc:422 Invalid arguments
    at TypeError (native)
    at WrappedImage.encode (E:\develop\workspaces\develop1.9.1\node_modules\_images@3.0.0@images\index.js:81:29)
    at WrappedImage.<anonymous> (E:\develop\workspaces\develop1.9.1\node_modules\_images@3.0.0@images\index.js:142:34)
    at WrappedImage.save (E:\develop\workspaces\develop1.9.1\node_modules\_images@3.0.0@images\index.js:88:37)
    at WrappedImage.save (E:\develop\workspaces\develop1.9.1\node_modules\_images@3.0.0@images\index.js:142:34)
    at E:\develop\workspaces\develop1.9.1\apimain.js:343:34
    at FSReqWrap.oncomplete (fs.js:123:15)】
---2017-5-25 15:7:39【TypeError: ..\src\Image.cc:422 Invalid arguments
    at TypeError (native)
    at WrappedImage.encode (E:\develop\workspaces\develop1.9.1\node_modules\_images@3.0.0@images\index.js:81:29)
    at WrappedImage.<anonymous> (E:\develop\workspaces\develop1.9.1\node_modules\_images@3.0.0@images\index.js:142:34)
    at WrappedImage.save (E:\develop\workspaces\develop1.9.1\node_modules\_images@3.0.0@images\index.js:88:37)
    at WrappedImage.save (E:\develop\workspaces\develop1.9.1\node_modules\_images@3.0.0@images\index.js:142:34)
    at E:\develop\workspaces\develop1.9.1\apimain.js:345:34
    at FSReqWrap.oncomplete (fs.js:123:15)】
---2017-5-25 15:8:34【TypeError: ..\src\Image.cc:422 Invalid arguments
    at TypeError (native)
    at WrappedImage.encode (E:\develop\workspaces\develop1.9.1\node_modules\_images@3.0.0@images\index.js:81:29)
    at WrappedImage.<anonymous> (E:\develop\workspaces\develop1.9.1\node_modules\_images@3.0.0@images\index.js:142:34)
    at WrappedImage.save (E:\develop\workspaces\develop1.9.1\node_modules\_images@3.0.0@images\index.js:88:37)
    at WrappedImage.save (E:\develop\workspaces\develop1.9.1\node_modules\_images@3.0.0@images\index.js:142:34)
    at E:\develop\workspaces\develop1.9.1\apimain.js:346:34
    at FSReqWrap.oncomplete (fs.js:123:15)】
---2017-5-25 15:9:9【TypeError: ..\src\Image.cc:422 Invalid arguments
    at TypeError (native)
    at WrappedImage.encode (E:\develop\workspaces\develop1.9.1\node_modules\_images@3.0.0@images\index.js:81:29)
    at WrappedImage.<anonymous> (E:\develop\workspaces\develop1.9.1\node_modules\_images@3.0.0@images\index.js:142:34)
    at WrappedImage.save (E:\develop\workspaces\develop1.9.1\node_modules\_images@3.0.0@images\index.js:88:37)
    at WrappedImage.save (E:\develop\workspaces\develop1.9.1\node_modules\_images@3.0.0@images\index.js:142:34)
    at E:\develop\workspaces\develop1.9.1\apimain.js:346:34
    at FSReqWrap.oncomplete (fs.js:123:15)】
---2017-5-25 15:10:24【TypeError: ..\src\Image.cc:422 Invalid arguments
    at TypeError (native)
    at WrappedImage.encode (E:\develop\workspaces\develop1.9.1\node_modules\_images@3.0.0@images\index.js:81:29)
    at WrappedImage.<anonymous> (E:\develop\workspaces\develop1.9.1\node_modules\_images@3.0.0@images\index.js:142:34)
    at WrappedImage.save (E:\develop\workspaces\develop1.9.1\node_modules\_images@3.0.0@images\index.js:88:37)
    at WrappedImage.save (E:\develop\workspaces\develop1.9.1\node_modules\_images@3.0.0@images\index.js:142:34)
    at E:\develop\workspaces\develop1.9.1\apimain.js:346:34
    at FSReqWrap.oncomplete (fs.js:123:15)】
---2017-5-25 15:12:24【TypeError: ..\src\Image.cc:422 Invalid arguments
    at TypeError (native)
    at WrappedImage.encode (E:\develop\workspaces\develop1.9.1\node_modules\_images@3.0.0@images\index.js:81:29)
    at WrappedImage.<anonymous> (E:\develop\workspaces\develop1.9.1\node_modules\_images@3.0.0@images\index.js:142:34)
    at WrappedImage.save (E:\develop\workspaces\develop1.9.1\node_modules\_images@3.0.0@images\index.js:88:37)
    at WrappedImage.save (E:\develop\workspaces\develop1.9.1\node_modules\_images@3.0.0@images\index.js:142:34)
    at E:\develop\workspaces\develop1.9.1\apimain.js:346:34
    at FSReqWrap.oncomplete (fs.js:123:15)】
---2017-5-25 17:22:6【error: 由于管理员命令中断联接
    at Connection.parseE (E:\develop\workspaces\develop1.9.1\node_modules\pg\lib\connection.js:539:11)
    at Connection.parseMessage (E:\develop\workspaces\develop1.9.1\node_modules\pg\lib\connection.js:366:17)
    at Socket.<anonymous> (E:\develop\workspaces\develop1.9.1\node_modules\pg\lib\connection.js:105:22)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
    at TCP.onread (net.js:547:20)】
---2017-5-25 17:22:6【error: 由于管理员命令中断联接
    at Connection.parseE (E:\develop\workspaces\develop1.9.1\node_modules\pg\lib\connection.js:539:11)
    at Connection.parseMessage (E:\develop\workspaces\develop1.9.1\node_modules\pg\lib\connection.js:366:17)
    at Socket.<anonymous> (E:\develop\workspaces\develop1.9.1\node_modules\pg\lib\connection.js:105:22)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
    at TCP.onread (net.js:547:20)】
---2017-5-25 17:22:6【error: 由于管理员命令中断联接
    at Connection.parseE (E:\develop\workspaces\develop1.9.1\node_modules\pg\lib\connection.js:539:11)
    at Connection.parseMessage (E:\develop\workspaces\develop1.9.1\node_modules\pg\lib\connection.js:366:17)
    at Socket.<anonymous> (E:\develop\workspaces\develop1.9.1\node_modules\pg\lib\connection.js:105:22)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
    at TCP.onread (net.js:547:20)】
---2017-5-25 17:22:6【error: 由于管理员命令中断联接
    at Connection.parseE (E:\develop\workspaces\develop1.9.1\node_modules\pg\lib\connection.js:539:11)
    at Connection.parseMessage (E:\develop\workspaces\develop1.9.1\node_modules\pg\lib\connection.js:366:17)
    at Socket.<anonymous> (E:\develop\workspaces\develop1.9.1\node_modules\pg\lib\connection.js:105:22)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
    at TCP.onread (net.js:547:20)】
---2017-5-25 17:22:6【error: 由于管理员命令中断联接
    at Connection.parseE (E:\develop\workspaces\develop1.9.1\node_modules\pg\lib\connection.js:539:11)
    at Connection.parseMessage (E:\develop\workspaces\develop1.9.1\node_modules\pg\lib\connection.js:366:17)
    at Socket.<anonymous> (E:\develop\workspaces\develop1.9.1\node_modules\pg\lib\connection.js:105:22)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
    at TCP.onread (net.js:547:20)】
---2017-5-25 17:22:6【error: 由于管理员命令中断联接
    at Connection.parseE (E:\develop\workspaces\develop1.9.1\node_modules\pg\lib\connection.js:539:11)
    at Connection.parseMessage (E:\develop\workspaces\develop1.9.1\node_modules\pg\lib\connection.js:366:17)
    at Socket.<anonymous> (E:\develop\workspaces\develop1.9.1\node_modules\pg\lib\connection.js:105:22)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
    at TCP.onread (net.js:547:20)】
---2017-5-25 17:22:6【error: 由于管理员命令中断联接
    at Connection.parseE (E:\develop\workspaces\develop1.9.1\node_modules\pg\lib\connection.js:539:11)
    at Connection.parseMessage (E:\develop\workspaces\develop1.9.1\node_modules\pg\lib\connection.js:366:17)
    at Socket.<anonymous> (E:\develop\workspaces\develop1.9.1\node_modules\pg\lib\connection.js:105:22)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
    at TCP.onread (net.js:547:20)】
---2017-5-25 17:22:6【error: 由于管理员命令中断联接
    at Connection.parseE (E:\develop\workspaces\develop1.9.1\node_modules\pg\lib\connection.js:539:11)
    at Connection.parseMessage (E:\develop\workspaces\develop1.9.1\node_modules\pg\lib\connection.js:366:17)
    at Socket.<anonymous> (E:\develop\workspaces\develop1.9.1\node_modules\pg\lib\connection.js:105:22)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
    at TCP.onread (net.js:547:20)】
---2017-5-25 17:22:6【error: 由于管理员命令中断联接
    at Connection.parseE (E:\develop\workspaces\develop1.9.1\node_modules\pg\lib\connection.js:539:11)
    at Connection.parseMessage (E:\develop\workspaces\develop1.9.1\node_modules\pg\lib\connection.js:366:17)
    at Socket.<anonymous> (E:\develop\workspaces\develop1.9.1\node_modules\pg\lib\connection.js:105:22)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
    at TCP.onread (net.js:547:20)】
---2017-5-25 17:22:6【error: 由于管理员命令中断联接
    at Connection.parseE (E:\develop\workspaces\develop1.9.1\node_modules\pg\lib\connection.js:539:11)
    at Connection.parseMessage (E:\develop\workspaces\develop1.9.1\node_modules\pg\lib\connection.js:366:17)
    at Socket.<anonymous> (E:\develop\workspaces\develop1.9.1\node_modules\pg\lib\connection.js:105:22)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
    at TCP.onread (net.js:547:20)】
---2017-5-25 17:22:7【error: 数据库系统停止中
    at Connection.parseE (E:\develop\workspaces\develop1.9.1\node_modules\pg\lib\connection.js:539:11)
    at Connection.parseMessage (E:\develop\workspaces\develop1.9.1\node_modules\pg\lib\connection.js:366:17)
    at Socket.<anonymous> (E:\develop\workspaces\develop1.9.1\node_modules\pg\lib\connection.js:105:22)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
    at TCP.onread (net.js:547:20)】
---2017-5-25 17:22:7【Error: Connection terminated
    at Connection.<anonymous> (E:\develop\workspaces\develop1.9.1\node_modules\pg\lib\client.js:183:17)
    at Connection.g (events.js:292:16)
    at emitNone (events.js:86:13)
    at Connection.emit (events.js:185:7)
    at Socket.<anonymous> (E:\develop\workspaces\develop1.9.1\node_modules\pg\lib\connection.js:66:10)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at TCP._handle.close [as _onclose] (net.js:497:12)】
