---2017-5-6 12:41:13【错误:连接PG数据库失败,错误信息:Error: connect ETIMEDOUT 192.168.0.100:5432】
---2017-5-6 12:41:13【Error: connect ETIMEDOUT 192.168.0.100:5432
    at Object.exports._errnoException (util.js:1018:11)
    at exports._exceptionWithHostPort (util.js:1041:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1086:14)】
---2017-5-6 12:41:13【错误:连接PG数据库失败,错误信息:Error: Connection terminated】
---2017-5-6 12:41:13【Error: Connection terminated
    at Connection.<anonymous> (E:\develop\workspaces\develop1.9.0\node_modules\pg\lib\client.js:183:17)
    at Connection.g (events.js:292:16)
    at emitNone (events.js:86:13)
    at Connection.emit (events.js:185:7)
    at Socket.<anonymous> (E:\develop\workspaces\develop1.9.0\node_modules\pg\lib\connection.js:66:10)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at TCP._handle.close [as _onclose] (net.js:497:12)】
---2017-5-6 12:43:10【Error: connect ETIMEDOUT 192.168.0.100:5432
    at Object.exports._errnoException (util.js:1018:11)
    at exports._exceptionWithHostPort (util.js:1041:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1086:14)】
---2017-5-6 12:43:10【Error: Connection terminated
    at Connection.<anonymous> (E:\develop\workspaces\develop1.9.0\node_modules\pg\lib\client.js:183:17)
    at Connection.g (events.js:292:16)
    at emitNone (events.js:86:13)
    at Connection.emit (events.js:185:7)
    at Socket.<anonymous> (E:\develop\workspaces\develop1.9.0\node_modules\pg\lib\connection.js:66:10)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at TCP._handle.close [as _onclose] (net.js:497:12)】
---2017-5-6 13:0:34【错误:连接PG数据库失败,错误信息:Error: connect ETIMEDOUT 192.168.0.100:5432】
---2017-5-6 13:0:34【Error: connect ETIMEDOUT 192.168.0.100:5432
    at Object.exports._errnoException (util.js:1018:11)
    at exports._exceptionWithHostPort (util.js:1041:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1086:14)】
---2017-5-6 13:0:34【Error: connect ETIMEDOUT 192.168.0.100:5432
    at Object.exports._errnoException (util.js:1018:11)
    at exports._exceptionWithHostPort (util.js:1041:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1086:14)】
---2017-5-6 13:0:34【Error: connect ETIMEDOUT 192.168.0.100:5432
    at Object.exports._errnoException (util.js:1018:11)
    at exports._exceptionWithHostPort (util.js:1041:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1086:14)】
---2017-5-6 13:0:34【Error: connect ETIMEDOUT 192.168.0.100:5432
    at Object.exports._errnoException (util.js:1018:11)
    at exports._exceptionWithHostPort (util.js:1041:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1086:14)】
---2017-5-6 13:0:34【Error: connect ETIMEDOUT 192.168.0.100:5432
    at Object.exports._errnoException (util.js:1018:11)
    at exports._exceptionWithHostPort (util.js:1041:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1086:14)】
---2017-5-6 13:0:34【Error: connect ETIMEDOUT 192.168.0.100:5432
    at Object.exports._errnoException (util.js:1018:11)
    at exports._exceptionWithHostPort (util.js:1041:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1086:14)】
---2017-5-6 13:0:34【Error: connect ETIMEDOUT 192.168.0.100:5432
    at Object.exports._errnoException (util.js:1018:11)
    at exports._exceptionWithHostPort (util.js:1041:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1086:14)】
---2017-5-6 13:0:34【Error: connect ETIMEDOUT 192.168.0.100:5432
    at Object.exports._errnoException (util.js:1018:11)
    at exports._exceptionWithHostPort (util.js:1041:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1086:14)】
---2017-5-6 13:0:34【Error: Connection terminated
    at Connection.<anonymous> (E:\develop\workspaces\develop1.9.0\node_modules\pg\lib\client.js:183:17)
    at Connection.g (events.js:292:16)
    at emitNone (events.js:86:13)
    at Connection.emit (events.js:185:7)
    at Socket.<anonymous> (E:\develop\workspaces\develop1.9.0\node_modules\pg\lib\connection.js:66:10)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at TCP._handle.close [as _onclose] (net.js:497:12)】
---2017-5-6 13:0:34【Error: Connection terminated
    at Connection.<anonymous> (E:\develop\workspaces\develop1.9.0\node_modules\pg\lib\client.js:183:17)
    at Connection.g (events.js:292:16)
    at emitNone (events.js:86:13)
    at Connection.emit (events.js:185:7)
    at Socket.<anonymous> (E:\develop\workspaces\develop1.9.0\node_modules\pg\lib\connection.js:66:10)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at TCP._handle.close [as _onclose] (net.js:497:12)】
---2017-5-6 13:0:34【Error: Connection terminated
    at Connection.<anonymous> (E:\develop\workspaces\develop1.9.0\node_modules\pg\lib\client.js:183:17)
    at Connection.g (events.js:292:16)
    at emitNone (events.js:86:13)
    at Connection.emit (events.js:185:7)
    at Socket.<anonymous> (E:\develop\workspaces\develop1.9.0\node_modules\pg\lib\connection.js:66:10)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at TCP._handle.close [as _onclose] (net.js:497:12)】
---2017-5-6 13:0:34【Error: Connection terminated
    at Connection.<anonymous> (E:\develop\workspaces\develop1.9.0\node_modules\pg\lib\client.js:183:17)
    at Connection.g (events.js:292:16)
    at emitNone (events.js:86:13)
    at Connection.emit (events.js:185:7)
    at Socket.<anonymous> (E:\develop\workspaces\develop1.9.0\node_modules\pg\lib\connection.js:66:10)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at TCP._handle.close [as _onclose] (net.js:497:12)】
---2017-5-6 13:0:34【Error: Connection terminated
    at Connection.<anonymous> (E:\develop\workspaces\develop1.9.0\node_modules\pg\lib\client.js:183:17)
    at Connection.g (events.js:292:16)
    at emitNone (events.js:86:13)
    at Connection.emit (events.js:185:7)
    at Socket.<anonymous> (E:\develop\workspaces\develop1.9.0\node_modules\pg\lib\connection.js:66:10)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at TCP._handle.close [as _onclose] (net.js:497:12)】
---2017-5-6 13:0:34【Error: Connection terminated
    at Connection.<anonymous> (E:\develop\workspaces\develop1.9.0\node_modules\pg\lib\client.js:183:17)
    at Connection.g (events.js:292:16)
    at emitNone (events.js:86:13)
    at Connection.emit (events.js:185:7)
    at Socket.<anonymous> (E:\develop\workspaces\develop1.9.0\node_modules\pg\lib\connection.js:66:10)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at TCP._handle.close [as _onclose] (net.js:497:12)】
---2017-5-6 13:0:34【Error: Connection terminated
    at Connection.<anonymous> (E:\develop\workspaces\develop1.9.0\node_modules\pg\lib\client.js:183:17)
    at Connection.g (events.js:292:16)
    at emitNone (events.js:86:13)
    at Connection.emit (events.js:185:7)
    at Socket.<anonymous> (E:\develop\workspaces\develop1.9.0\node_modules\pg\lib\connection.js:66:10)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at TCP._handle.close [as _onclose] (net.js:497:12)】
---2017-5-6 13:0:34【Error: Connection terminated
    at Connection.<anonymous> (E:\develop\workspaces\develop1.9.0\node_modules\pg\lib\client.js:183:17)
    at Connection.g (events.js:292:16)
    at emitNone (events.js:86:13)
    at Connection.emit (events.js:185:7)
    at Socket.<anonymous> (E:\develop\workspaces\develop1.9.0\node_modules\pg\lib\connection.js:66:10)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at TCP._handle.close [as _onclose] (net.js:497:12)】
---2017-5-6 13:0:34【Error: connect ETIMEDOUT 192.168.0.100:5432
    at Object.exports._errnoException (util.js:1018:11)
    at exports._exceptionWithHostPort (util.js:1041:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1086:14)】
---2017-5-6 13:0:34【Error: connect ETIMEDOUT 192.168.0.100:5432
    at Object.exports._errnoException (util.js:1018:11)
    at exports._exceptionWithHostPort (util.js:1041:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1086:14)】
---2017-5-6 13:0:34【Error: connect ETIMEDOUT 192.168.0.100:5432
    at Object.exports._errnoException (util.js:1018:11)
    at exports._exceptionWithHostPort (util.js:1041:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1086:14)】
---2017-5-6 13:0:34【Error: Connection terminated
    at Connection.<anonymous> (E:\develop\workspaces\develop1.9.0\node_modules\pg\lib\client.js:183:17)
    at Connection.g (events.js:292:16)
    at emitNone (events.js:86:13)
    at Connection.emit (events.js:185:7)
    at Socket.<anonymous> (E:\develop\workspaces\develop1.9.0\node_modules\pg\lib\connection.js:66:10)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at TCP._handle.close [as _onclose] (net.js:497:12)】
---2017-5-6 13:0:34【Error: Connection terminated
    at Connection.<anonymous> (E:\develop\workspaces\develop1.9.0\node_modules\pg\lib\client.js:183:17)
    at Connection.g (events.js:292:16)
    at emitNone (events.js:86:13)
    at Connection.emit (events.js:185:7)
    at Socket.<anonymous> (E:\develop\workspaces\develop1.9.0\node_modules\pg\lib\connection.js:66:10)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at TCP._handle.close [as _onclose] (net.js:497:12)】
---2017-5-6 13:0:34【Error: Connection terminated
    at Connection.<anonymous> (E:\develop\workspaces\develop1.9.0\node_modules\pg\lib\client.js:183:17)
    at Connection.g (events.js:292:16)
    at emitNone (events.js:86:13)
    at Connection.emit (events.js:185:7)
    at Socket.<anonymous> (E:\develop\workspaces\develop1.9.0\node_modules\pg\lib\connection.js:66:10)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at TCP._handle.close [as _onclose] (net.js:497:12)】
---2017-5-6 13:2:53【Error: connect ETIMEDOUT 192.168.0.100:5432
    at Object.exports._errnoException (util.js:1018:11)
    at exports._exceptionWithHostPort (util.js:1041:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1086:14)】
---2017-5-6 13:2:53【Error: Connection terminated
    at Connection.<anonymous> (E:\develop\workspaces\develop1.9.0\node_modules\pg\lib\client.js:183:17)
    at Connection.g (events.js:292:16)
    at emitNone (events.js:86:13)
    at Connection.emit (events.js:185:7)
    at Socket.<anonymous> (E:\develop\workspaces\develop1.9.0\node_modules\pg\lib\connection.js:66:10)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at TCP._handle.close [as _onclose] (net.js:497:12)】
---2017-5-6 13:4:26【Error: connect ETIMEDOUT 192.168.0.100:5432
    at Object.exports._errnoException (util.js:1018:11)
    at exports._exceptionWithHostPort (util.js:1041:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1086:14)】
---2017-5-6 13:4:26【Error: Connection terminated
    at Connection.<anonymous> (E:\develop\workspaces\develop1.9.0\node_modules\pg\lib\client.js:183:17)
    at Connection.g (events.js:292:16)
    at emitNone (events.js:86:13)
    at Connection.emit (events.js:185:7)
    at Socket.<anonymous> (E:\develop\workspaces\develop1.9.0\node_modules\pg\lib\connection.js:66:10)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at TCP._handle.close [as _onclose] (net.js:497:12)】
---2017-5-6 13:4:26【Error: connect ETIMEDOUT 192.168.0.100:5432
    at Object.exports._errnoException (util.js:1018:11)
    at exports._exceptionWithHostPort (util.js:1041:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1086:14)】
---2017-5-6 13:4:26【Error: connect ETIMEDOUT 192.168.0.100:5432
    at Object.exports._errnoException (util.js:1018:11)
    at exports._exceptionWithHostPort (util.js:1041:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1086:14)】
---2017-5-6 13:4:26【Error: Connection terminated
    at Connection.<anonymous> (E:\develop\workspaces\develop1.9.0\node_modules\pg\lib\client.js:183:17)
    at Connection.g (events.js:292:16)
    at emitNone (events.js:86:13)
    at Connection.emit (events.js:185:7)
    at Socket.<anonymous> (E:\develop\workspaces\develop1.9.0\node_modules\pg\lib\connection.js:66:10)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at TCP._handle.close [as _onclose] (net.js:497:12)】
---2017-5-6 13:4:26【Error: Connection terminated
    at Connection.<anonymous> (E:\develop\workspaces\develop1.9.0\node_modules\pg\lib\client.js:183:17)
    at Connection.g (events.js:292:16)
    at emitNone (events.js:86:13)
    at Connection.emit (events.js:185:7)
    at Socket.<anonymous> (E:\develop\workspaces\develop1.9.0\node_modules\pg\lib\connection.js:66:10)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at TCP._handle.close [as _onclose] (net.js:497:12)】
---2017-5-6 13:4:27【Error: connect ETIMEDOUT 192.168.0.100:5432
    at Object.exports._errnoException (util.js:1018:11)
    at exports._exceptionWithHostPort (util.js:1041:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1086:14)】
---2017-5-6 13:4:27【Error: Connection terminated
    at Connection.<anonymous> (E:\develop\workspaces\develop1.9.0\node_modules\pg\lib\client.js:183:17)
    at Connection.g (events.js:292:16)
    at emitNone (events.js:86:13)
    at Connection.emit (events.js:185:7)
    at Socket.<anonymous> (E:\develop\workspaces\develop1.9.0\node_modules\pg\lib\connection.js:66:10)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at TCP._handle.close [as _onclose] (net.js:497:12)】
---2017-5-6 13:6:0【Error: connect ETIMEDOUT 192.168.0.100:5432
    at Object.exports._errnoException (util.js:1018:11)
    at exports._exceptionWithHostPort (util.js:1041:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1086:14)】
---2017-5-6 13:6:0【Error: Connection terminated
    at Connection.<anonymous> (E:\develop\workspaces\develop1.9.0\node_modules\pg\lib\client.js:183:17)
    at Connection.g (events.js:292:16)
    at emitNone (events.js:86:13)
    at Connection.emit (events.js:185:7)
    at Socket.<anonymous> (E:\develop\workspaces\develop1.9.0\node_modules\pg\lib\connection.js:66:10)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at TCP._handle.close [as _onclose] (net.js:497:12)】
---2017-5-6 13:6:0【Error: connect ETIMEDOUT 192.168.0.100:5432
    at Object.exports._errnoException (util.js:1018:11)
    at exports._exceptionWithHostPort (util.js:1041:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1086:14)】
---2017-5-6 13:6:0【Error: connect ETIMEDOUT 192.168.0.100:5432
    at Object.exports._errnoException (util.js:1018:11)
    at exports._exceptionWithHostPort (util.js:1041:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1086:14)】
---2017-5-6 13:6:0【Error: connect ETIMEDOUT 192.168.0.100:5432
    at Object.exports._errnoException (util.js:1018:11)
    at exports._exceptionWithHostPort (util.js:1041:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1086:14)】
---2017-5-6 13:6:0【Error: connect ETIMEDOUT 192.168.0.100:5432
    at Object.exports._errnoException (util.js:1018:11)
    at exports._exceptionWithHostPort (util.js:1041:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1086:14)】
---2017-5-6 13:6:0【Error: Connection terminated
    at Connection.<anonymous> (E:\develop\workspaces\develop1.9.0\node_modules\pg\lib\client.js:183:17)
    at Connection.g (events.js:292:16)
    at emitNone (events.js:86:13)
    at Connection.emit (events.js:185:7)
    at Socket.<anonymous> (E:\develop\workspaces\develop1.9.0\node_modules\pg\lib\connection.js:66:10)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at TCP._handle.close [as _onclose] (net.js:497:12)】
---2017-5-6 13:6:0【Error: Connection terminated
    at Connection.<anonymous> (E:\develop\workspaces\develop1.9.0\node_modules\pg\lib\client.js:183:17)
    at Connection.g (events.js:292:16)
    at emitNone (events.js:86:13)
    at Connection.emit (events.js:185:7)
    at Socket.<anonymous> (E:\develop\workspaces\develop1.9.0\node_modules\pg\lib\connection.js:66:10)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at TCP._handle.close [as _onclose] (net.js:497:12)】
---2017-5-6 13:6:0【Error: Connection terminated
    at Connection.<anonymous> (E:\develop\workspaces\develop1.9.0\node_modules\pg\lib\client.js:183:17)
    at Connection.g (events.js:292:16)
    at emitNone (events.js:86:13)
    at Connection.emit (events.js:185:7)
    at Socket.<anonymous> (E:\develop\workspaces\develop1.9.0\node_modules\pg\lib\connection.js:66:10)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at TCP._handle.close [as _onclose] (net.js:497:12)】
---2017-5-6 13:6:0【Error: Connection terminated
    at Connection.<anonymous> (E:\develop\workspaces\develop1.9.0\node_modules\pg\lib\client.js:183:17)
    at Connection.g (events.js:292:16)
    at emitNone (events.js:86:13)
    at Connection.emit (events.js:185:7)
    at Socket.<anonymous> (E:\develop\workspaces\develop1.9.0\node_modules\pg\lib\connection.js:66:10)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at TCP._handle.close [as _onclose] (net.js:497:12)】
---2017-5-6 13:6:0【Error: connect ETIMEDOUT 192.168.0.100:5432
    at Object.exports._errnoException (util.js:1018:11)
    at exports._exceptionWithHostPort (util.js:1041:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1086:14)】
---2017-5-6 13:6:0【Error: connect ETIMEDOUT 192.168.0.100:5432
    at Object.exports._errnoException (util.js:1018:11)
    at exports._exceptionWithHostPort (util.js:1041:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1086:14)】
---2017-5-6 13:6:0【Error: connect ETIMEDOUT 192.168.0.100:5432
    at Object.exports._errnoException (util.js:1018:11)
    at exports._exceptionWithHostPort (util.js:1041:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1086:14)】
---2017-5-6 13:6:0【Error: connect ETIMEDOUT 192.168.0.100:5432
    at Object.exports._errnoException (util.js:1018:11)
    at exports._exceptionWithHostPort (util.js:1041:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1086:14)】
---2017-5-6 13:6:0【Error: Connection terminated
    at Connection.<anonymous> (E:\develop\workspaces\develop1.9.0\node_modules\pg\lib\client.js:183:17)
    at Connection.g (events.js:292:16)
    at emitNone (events.js:86:13)
    at Connection.emit (events.js:185:7)
    at Socket.<anonymous> (E:\develop\workspaces\develop1.9.0\node_modules\pg\lib\connection.js:66:10)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at TCP._handle.close [as _onclose] (net.js:497:12)】
---2017-5-6 13:6:0【Error: Connection terminated
    at Connection.<anonymous> (E:\develop\workspaces\develop1.9.0\node_modules\pg\lib\client.js:183:17)
    at Connection.g (events.js:292:16)
    at emitNone (events.js:86:13)
    at Connection.emit (events.js:185:7)
    at Socket.<anonymous> (E:\develop\workspaces\develop1.9.0\node_modules\pg\lib\connection.js:66:10)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at TCP._handle.close [as _onclose] (net.js:497:12)】
---2017-5-6 13:6:0【Error: Connection terminated
    at Connection.<anonymous> (E:\develop\workspaces\develop1.9.0\node_modules\pg\lib\client.js:183:17)
    at Connection.g (events.js:292:16)
    at emitNone (events.js:86:13)
    at Connection.emit (events.js:185:7)
    at Socket.<anonymous> (E:\develop\workspaces\develop1.9.0\node_modules\pg\lib\connection.js:66:10)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at TCP._handle.close [as _onclose] (net.js:497:12)】
---2017-5-6 13:6:0【Error: Connection terminated
    at Connection.<anonymous> (E:\develop\workspaces\develop1.9.0\node_modules\pg\lib\client.js:183:17)
    at Connection.g (events.js:292:16)
    at emitNone (events.js:86:13)
    at Connection.emit (events.js:185:7)
    at Socket.<anonymous> (E:\develop\workspaces\develop1.9.0\node_modules\pg\lib\connection.js:66:10)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at TCP._handle.close [as _onclose] (net.js:497:12)】
---2017-5-6 13:6:1【Error: connect ETIMEDOUT 192.168.0.100:5432
    at Object.exports._errnoException (util.js:1018:11)
    at exports._exceptionWithHostPort (util.js:1041:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1086:14)】
---2017-5-6 13:6:1【Error: Connection terminated
    at Connection.<anonymous> (E:\develop\workspaces\develop1.9.0\node_modules\pg\lib\client.js:183:17)
    at Connection.g (events.js:292:16)
    at emitNone (events.js:86:13)
    at Connection.emit (events.js:185:7)
    at Socket.<anonymous> (E:\develop\workspaces\develop1.9.0\node_modules\pg\lib\connection.js:66:10)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at TCP._handle.close [as _onclose] (net.js:497:12)】
---2017-5-6 13:6:1【Error: connect ETIMEDOUT 192.168.0.100:5432
    at Object.exports._errnoException (util.js:1018:11)
    at exports._exceptionWithHostPort (util.js:1041:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1086:14)】
---2017-5-6 13:6:1【Error: connect ETIMEDOUT 192.168.0.100:5432
    at Object.exports._errnoException (util.js:1018:11)
    at exports._exceptionWithHostPort (util.js:1041:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1086:14)】
---2017-5-6 13:6:1【Error: connect ETIMEDOUT 192.168.0.100:5432
    at Object.exports._errnoException (util.js:1018:11)
    at exports._exceptionWithHostPort (util.js:1041:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1086:14)】
---2017-5-6 13:6:1【Error: Connection terminated
    at Connection.<anonymous> (E:\develop\workspaces\develop1.9.0\node_modules\pg\lib\client.js:183:17)
    at Connection.g (events.js:292:16)
    at emitNone (events.js:86:13)
    at Connection.emit (events.js:185:7)
    at Socket.<anonymous> (E:\develop\workspaces\develop1.9.0\node_modules\pg\lib\connection.js:66:10)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at TCP._handle.close [as _onclose] (net.js:497:12)】
---2017-5-6 13:6:1【Error: Connection terminated
    at Connection.<anonymous> (E:\develop\workspaces\develop1.9.0\node_modules\pg\lib\client.js:183:17)
    at Connection.g (events.js:292:16)
    at emitNone (events.js:86:13)
    at Connection.emit (events.js:185:7)
    at Socket.<anonymous> (E:\develop\workspaces\develop1.9.0\node_modules\pg\lib\connection.js:66:10)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at TCP._handle.close [as _onclose] (net.js:497:12)】
---2017-5-6 13:6:1【Error: Connection terminated
    at Connection.<anonymous> (E:\develop\workspaces\develop1.9.0\node_modules\pg\lib\client.js:183:17)
    at Connection.g (events.js:292:16)
    at emitNone (events.js:86:13)
    at Connection.emit (events.js:185:7)
    at Socket.<anonymous> (E:\develop\workspaces\develop1.9.0\node_modules\pg\lib\connection.js:66:10)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at TCP._handle.close [as _onclose] (net.js:497:12)】
---2017-5-6 13:6:10【Error: connect ETIMEDOUT 192.168.0.100:5432
    at Object.exports._errnoException (util.js:1018:11)
    at exports._exceptionWithHostPort (util.js:1041:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1086:14)】
---2017-5-6 13:6:10【Error: Connection terminated
    at Connection.<anonymous> (E:\develop\workspaces\develop1.9.0\node_modules\pg\lib\client.js:183:17)
    at Connection.g (events.js:292:16)
    at emitNone (events.js:86:13)
    at Connection.emit (events.js:185:7)
    at Socket.<anonymous> (E:\develop\workspaces\develop1.9.0\node_modules\pg\lib\connection.js:66:10)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at TCP._handle.close [as _onclose] (net.js:497:12)】
---2017-5-6 13:7:43【Error: connect ETIMEDOUT 192.168.0.100:5432
    at Object.exports._errnoException (util.js:1018:11)
    at exports._exceptionWithHostPort (util.js:1041:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1086:14)】
---2017-5-6 13:7:43【Error: connect ETIMEDOUT 192.168.0.100:5432
    at Object.exports._errnoException (util.js:1018:11)
    at exports._exceptionWithHostPort (util.js:1041:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1086:14)】
---2017-5-6 13:7:43【Error: Connection terminated
    at Connection.<anonymous> (E:\develop\workspaces\develop1.9.0\node_modules\pg\lib\client.js:183:17)
    at Connection.g (events.js:292:16)
    at emitNone (events.js:86:13)
    at Connection.emit (events.js:185:7)
    at Socket.<anonymous> (E:\develop\workspaces\develop1.9.0\node_modules\pg\lib\connection.js:66:10)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at TCP._handle.close [as _onclose] (net.js:497:12)】
---2017-5-6 13:7:43【Error: Connection terminated
    at Connection.<anonymous> (E:\develop\workspaces\develop1.9.0\node_modules\pg\lib\client.js:183:17)
    at Connection.g (events.js:292:16)
    at emitNone (events.js:86:13)
    at Connection.emit (events.js:185:7)
    at Socket.<anonymous> (E:\develop\workspaces\develop1.9.0\node_modules\pg\lib\connection.js:66:10)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at TCP._handle.close [as _onclose] (net.js:497:12)】
---2017-5-6 13:7:43【Error: connect ETIMEDOUT 192.168.0.100:5432
    at Object.exports._errnoException (util.js:1018:11)
    at exports._exceptionWithHostPort (util.js:1041:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1086:14)】
---2017-5-6 13:7:43【Error: connect ETIMEDOUT 192.168.0.100:5432
    at Object.exports._errnoException (util.js:1018:11)
    at exports._exceptionWithHostPort (util.js:1041:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1086:14)】
---2017-5-6 13:7:43【Error: connect ETIMEDOUT 192.168.0.100:5432
    at Object.exports._errnoException (util.js:1018:11)
    at exports._exceptionWithHostPort (util.js:1041:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1086:14)】
---2017-5-6 13:7:43【Error: connect ETIMEDOUT 192.168.0.100:5432
    at Object.exports._errnoException (util.js:1018:11)
    at exports._exceptionWithHostPort (util.js:1041:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1086:14)】
---2017-5-6 13:7:43【Error: connect ETIMEDOUT 192.168.0.100:5432
    at Object.exports._errnoException (util.js:1018:11)
    at exports._exceptionWithHostPort (util.js:1041:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1086:14)】
---2017-5-6 13:7:43【Error: Connection terminated
    at Connection.<anonymous> (E:\develop\workspaces\develop1.9.0\node_modules\pg\lib\client.js:183:17)
    at Connection.g (events.js:292:16)
    at emitNone (events.js:86:13)
    at Connection.emit (events.js:185:7)
    at Socket.<anonymous> (E:\develop\workspaces\develop1.9.0\node_modules\pg\lib\connection.js:66:10)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at TCP._handle.close [as _onclose] (net.js:497:12)】
---2017-5-6 13:7:43【Error: Connection terminated
    at Connection.<anonymous> (E:\develop\workspaces\develop1.9.0\node_modules\pg\lib\client.js:183:17)
    at Connection.g (events.js:292:16)
    at emitNone (events.js:86:13)
    at Connection.emit (events.js:185:7)
    at Socket.<anonymous> (E:\develop\workspaces\develop1.9.0\node_modules\pg\lib\connection.js:66:10)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at TCP._handle.close [as _onclose] (net.js:497:12)】
---2017-5-6 13:7:43【Error: Connection terminated
    at Connection.<anonymous> (E:\develop\workspaces\develop1.9.0\node_modules\pg\lib\client.js:183:17)
    at Connection.g (events.js:292:16)
    at emitNone (events.js:86:13)
    at Connection.emit (events.js:185:7)
    at Socket.<anonymous> (E:\develop\workspaces\develop1.9.0\node_modules\pg\lib\connection.js:66:10)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at TCP._handle.close [as _onclose] (net.js:497:12)】
---2017-5-6 13:7:43【Error: Connection terminated
    at Connection.<anonymous> (E:\develop\workspaces\develop1.9.0\node_modules\pg\lib\client.js:183:17)
    at Connection.g (events.js:292:16)
    at emitNone (events.js:86:13)
    at Connection.emit (events.js:185:7)
    at Socket.<anonymous> (E:\develop\workspaces\develop1.9.0\node_modules\pg\lib\connection.js:66:10)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at TCP._handle.close [as _onclose] (net.js:497:12)】
---2017-5-6 13:7:43【Error: Connection terminated
    at Connection.<anonymous> (E:\develop\workspaces\develop1.9.0\node_modules\pg\lib\client.js:183:17)
    at Connection.g (events.js:292:16)
    at emitNone (events.js:86:13)
    at Connection.emit (events.js:185:7)
    at Socket.<anonymous> (E:\develop\workspaces\develop1.9.0\node_modules\pg\lib\connection.js:66:10)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at TCP._handle.close [as _onclose] (net.js:497:12)】
---2017-5-6 13:7:43【Error: connect ETIMEDOUT 192.168.0.100:5432
    at Object.exports._errnoException (util.js:1018:11)
    at exports._exceptionWithHostPort (util.js:1041:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1086:14)】
---2017-5-6 13:7:43【Error: connect ETIMEDOUT 192.168.0.100:5432
    at Object.exports._errnoException (util.js:1018:11)
    at exports._exceptionWithHostPort (util.js:1041:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1086:14)】
---2017-5-6 13:7:43【Error: connect ETIMEDOUT 192.168.0.100:5432
    at Object.exports._errnoException (util.js:1018:11)
    at exports._exceptionWithHostPort (util.js:1041:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1086:14)】
---2017-5-6 13:7:43【Error: Connection terminated
    at Connection.<anonymous> (E:\develop\workspaces\develop1.9.0\node_modules\pg\lib\client.js:183:17)
    at Connection.g (events.js:292:16)
    at emitNone (events.js:86:13)
    at Connection.emit (events.js:185:7)
    at Socket.<anonymous> (E:\develop\workspaces\develop1.9.0\node_modules\pg\lib\connection.js:66:10)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at TCP._handle.close [as _onclose] (net.js:497:12)】
---2017-5-6 13:7:43【Error: Connection terminated
    at Connection.<anonymous> (E:\develop\workspaces\develop1.9.0\node_modules\pg\lib\client.js:183:17)
    at Connection.g (events.js:292:16)
    at emitNone (events.js:86:13)
    at Connection.emit (events.js:185:7)
    at Socket.<anonymous> (E:\develop\workspaces\develop1.9.0\node_modules\pg\lib\connection.js:66:10)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at TCP._handle.close [as _onclose] (net.js:497:12)】
---2017-5-6 13:7:43【Error: Connection terminated
    at Connection.<anonymous> (E:\develop\workspaces\develop1.9.0\node_modules\pg\lib\client.js:183:17)
    at Connection.g (events.js:292:16)
    at emitNone (events.js:86:13)
    at Connection.emit (events.js:185:7)
    at Socket.<anonymous> (E:\develop\workspaces\develop1.9.0\node_modules\pg\lib\connection.js:66:10)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at TCP._handle.close [as _onclose] (net.js:497:12)】
---2017-5-6 13:38:51【Error: connect ETIMEDOUT 192.168.0.100:5432
    at Object.exports._errnoException (util.js:1018:11)
    at exports._exceptionWithHostPort (util.js:1041:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1086:14)】
---2017-5-6 13:38:51【Error: Connection terminated
    at Connection.<anonymous> (E:\develop\workspaces\develop1.9.0\node_modules\pg\lib\client.js:183:17)
    at Connection.g (events.js:292:16)
    at emitNone (events.js:86:13)
    at Connection.emit (events.js:185:7)
    at Socket.<anonymous> (E:\develop\workspaces\develop1.9.0\node_modules\pg\lib\connection.js:66:10)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at TCP._handle.close [as _onclose] (net.js:497:12)】
---2017-5-6 13:38:51【Error: connect ETIMEDOUT 192.168.0.100:5432
    at Object.exports._errnoException (util.js:1018:11)
    at exports._exceptionWithHostPort (util.js:1041:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1086:14)】
---2017-5-6 13:38:51【Error: connect ETIMEDOUT 192.168.0.100:5432
    at Object.exports._errnoException (util.js:1018:11)
    at exports._exceptionWithHostPort (util.js:1041:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1086:14)】
---2017-5-6 13:38:51【Error: connect ETIMEDOUT 192.168.0.100:5432
    at Object.exports._errnoException (util.js:1018:11)
    at exports._exceptionWithHostPort (util.js:1041:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1086:14)】
---2017-5-6 13:38:51【Error: connect ETIMEDOUT 192.168.0.100:5432
    at Object.exports._errnoException (util.js:1018:11)
    at exports._exceptionWithHostPort (util.js:1041:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1086:14)】
---2017-5-6 13:38:51【Error: connect ETIMEDOUT 192.168.0.100:5432
    at Object.exports._errnoException (util.js:1018:11)
    at exports._exceptionWithHostPort (util.js:1041:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1086:14)】
---2017-5-6 13:38:51【Error: connect ETIMEDOUT 192.168.0.100:5432
    at Object.exports._errnoException (util.js:1018:11)
    at exports._exceptionWithHostPort (util.js:1041:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1086:14)】
---2017-5-6 13:38:51【Error: connect ETIMEDOUT 192.168.0.100:5432
    at Object.exports._errnoException (util.js:1018:11)
    at exports._exceptionWithHostPort (util.js:1041:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1086:14)】
---2017-5-6 13:38:51【Error: connect ETIMEDOUT 192.168.0.100:5432
    at Object.exports._errnoException (util.js:1018:11)
    at exports._exceptionWithHostPort (util.js:1041:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1086:14)】
---2017-5-6 13:38:51【Error: connect ETIMEDOUT 192.168.0.100:5432
    at Object.exports._errnoException (util.js:1018:11)
    at exports._exceptionWithHostPort (util.js:1041:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1086:14)】
---2017-5-6 13:38:51【Error: Connection terminated
    at Connection.<anonymous> (E:\develop\workspaces\develop1.9.0\node_modules\pg\lib\client.js:183:17)
    at Connection.g (events.js:292:16)
    at emitNone (events.js:86:13)
    at Connection.emit (events.js:185:7)
    at Socket.<anonymous> (E:\develop\workspaces\develop1.9.0\node_modules\pg\lib\connection.js:66:10)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at TCP._handle.close [as _onclose] (net.js:497:12)】
---2017-5-6 13:38:51【Error: Connection terminated
    at Connection.<anonymous> (E:\develop\workspaces\develop1.9.0\node_modules\pg\lib\client.js:183:17)
    at Connection.g (events.js:292:16)
    at emitNone (events.js:86:13)
    at Connection.emit (events.js:185:7)
    at Socket.<anonymous> (E:\develop\workspaces\develop1.9.0\node_modules\pg\lib\connection.js:66:10)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at TCP._handle.close [as _onclose] (net.js:497:12)】
---2017-5-6 13:38:51【Error: Connection terminated
    at Connection.<anonymous> (E:\develop\workspaces\develop1.9.0\node_modules\pg\lib\client.js:183:17)
    at Connection.g (events.js:292:16)
    at emitNone (events.js:86:13)
    at Connection.emit (events.js:185:7)
    at Socket.<anonymous> (E:\develop\workspaces\develop1.9.0\node_modules\pg\lib\connection.js:66:10)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at TCP._handle.close [as _onclose] (net.js:497:12)】
---2017-5-6 13:38:51【Error: Connection terminated
    at Connection.<anonymous> (E:\develop\workspaces\develop1.9.0\node_modules\pg\lib\client.js:183:17)
    at Connection.g (events.js:292:16)
    at emitNone (events.js:86:13)
    at Connection.emit (events.js:185:7)
    at Socket.<anonymous> (E:\develop\workspaces\develop1.9.0\node_modules\pg\lib\connection.js:66:10)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at TCP._handle.close [as _onclose] (net.js:497:12)】
---2017-5-6 13:38:51【Error: Connection terminated
    at Connection.<anonymous> (E:\develop\workspaces\develop1.9.0\node_modules\pg\lib\client.js:183:17)
    at Connection.g (events.js:292:16)
    at emitNone (events.js:86:13)
    at Connection.emit (events.js:185:7)
    at Socket.<anonymous> (E:\develop\workspaces\develop1.9.0\node_modules\pg\lib\connection.js:66:10)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at TCP._handle.close [as _onclose] (net.js:497:12)】
---2017-5-6 13:38:51【Error: Connection terminated
    at Connection.<anonymous> (E:\develop\workspaces\develop1.9.0\node_modules\pg\lib\client.js:183:17)
    at Connection.g (events.js:292:16)
    at emitNone (events.js:86:13)
    at Connection.emit (events.js:185:7)
    at Socket.<anonymous> (E:\develop\workspaces\develop1.9.0\node_modules\pg\lib\connection.js:66:10)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at TCP._handle.close [as _onclose] (net.js:497:12)】
---2017-5-6 13:38:51【Error: Connection terminated
    at Connection.<anonymous> (E:\develop\workspaces\develop1.9.0\node_modules\pg\lib\client.js:183:17)
    at Connection.g (events.js:292:16)
    at emitNone (events.js:86:13)
    at Connection.emit (events.js:185:7)
    at Socket.<anonymous> (E:\develop\workspaces\develop1.9.0\node_modules\pg\lib\connection.js:66:10)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at TCP._handle.close [as _onclose] (net.js:497:12)】
---2017-5-6 13:38:51【Error: Connection terminated
    at Connection.<anonymous> (E:\develop\workspaces\develop1.9.0\node_modules\pg\lib\client.js:183:17)
    at Connection.g (events.js:292:16)
    at emitNone (events.js:86:13)
    at Connection.emit (events.js:185:7)
    at Socket.<anonymous> (E:\develop\workspaces\develop1.9.0\node_modules\pg\lib\connection.js:66:10)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at TCP._handle.close [as _onclose] (net.js:497:12)】
---2017-5-6 13:38:51【Error: Connection terminated
    at Connection.<anonymous> (E:\develop\workspaces\develop1.9.0\node_modules\pg\lib\client.js:183:17)
    at Connection.g (events.js:292:16)
    at emitNone (events.js:86:13)
    at Connection.emit (events.js:185:7)
    at Socket.<anonymous> (E:\develop\workspaces\develop1.9.0\node_modules\pg\lib\connection.js:66:10)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at TCP._handle.close [as _onclose] (net.js:497:12)】
---2017-5-6 13:57:51【error: terminating connection due to administrator command
    at Connection.parseE (E:\develop\workspaces\develop1.9.0\node_modules\pg\lib\connection.js:539:11)
    at Connection.parseMessage (E:\develop\workspaces\develop1.9.0\node_modules\pg\lib\connection.js:366:17)
    at Socket.<anonymous> (E:\develop\workspaces\develop1.9.0\node_modules\pg\lib\connection.js:105:22)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
    at TCP.onread (net.js:547:20)】
---2017-5-6 13:57:51【Error: read ECONNRESET
    at exports._errnoException (util.js:1018:11)
    at TCP.onread (net.js:568:26)】
---2017-5-6 13:57:51【error: terminating connection due to administrator command
    at Connection.parseE (E:\develop\workspaces\develop1.9.0\node_modules\pg\lib\connection.js:539:11)
    at Connection.parseMessage (E:\develop\workspaces\develop1.9.0\node_modules\pg\lib\connection.js:366:17)
    at Socket.<anonymous> (E:\develop\workspaces\develop1.9.0\node_modules\pg\lib\connection.js:105:22)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
    at TCP.onread (net.js:547:20)】
---2017-5-6 13:57:51【Error: read ECONNRESET
    at exports._errnoException (util.js:1018:11)
    at TCP.onread (net.js:568:26)】
---2017-5-6 13:57:51【error: terminating connection due to administrator command
    at Connection.parseE (E:\develop\workspaces\develop1.9.0\node_modules\pg\lib\connection.js:539:11)
    at Connection.parseMessage (E:\develop\workspaces\develop1.9.0\node_modules\pg\lib\connection.js:366:17)
    at Socket.<anonymous> (E:\develop\workspaces\develop1.9.0\node_modules\pg\lib\connection.js:105:22)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
    at TCP.onread (net.js:547:20)】
---2017-5-6 13:57:51【Error: read ECONNRESET
    at exports._errnoException (util.js:1018:11)
    at TCP.onread (net.js:568:26)】
---2017-5-6 13:57:51【error: terminating connection due to administrator command
    at Connection.parseE (E:\develop\workspaces\develop1.9.0\node_modules\pg\lib\connection.js:539:11)
    at Connection.parseMessage (E:\develop\workspaces\develop1.9.0\node_modules\pg\lib\connection.js:366:17)
    at Socket.<anonymous> (E:\develop\workspaces\develop1.9.0\node_modules\pg\lib\connection.js:105:22)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
    at TCP.onread (net.js:547:20)】
---2017-5-6 13:57:51【Error: read ECONNRESET
    at exports._errnoException (util.js:1018:11)
    at TCP.onread (net.js:568:26)】
---2017-5-6 13:57:51【Error: read ECONNRESET
    at exports._errnoException (util.js:1018:11)
    at TCP.onread (net.js:568:26)】
---2017-5-6 13:57:51【error: terminating connection due to administrator command
    at Connection.parseE (E:\develop\workspaces\develop1.9.0\node_modules\pg\lib\connection.js:539:11)
    at Connection.parseMessage (E:\develop\workspaces\develop1.9.0\node_modules\pg\lib\connection.js:366:17)
    at Socket.<anonymous> (E:\develop\workspaces\develop1.9.0\node_modules\pg\lib\connection.js:105:22)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
    at TCP.onread (net.js:547:20)】
---2017-5-6 13:57:51【Error: read ECONNRESET
    at exports._errnoException (util.js:1018:11)
    at TCP.onread (net.js:568:26)】
---2017-5-6 13:57:51【error: terminating connection due to administrator command
    at Connection.parseE (E:\develop\workspaces\develop1.9.0\node_modules\pg\lib\connection.js:539:11)
    at Connection.parseMessage (E:\develop\workspaces\develop1.9.0\node_modules\pg\lib\connection.js:366:17)
    at Socket.<anonymous> (E:\develop\workspaces\develop1.9.0\node_modules\pg\lib\connection.js:105:22)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
    at TCP.onread (net.js:547:20)】
---2017-5-6 13:57:51【Error: read ECONNRESET
    at exports._errnoException (util.js:1018:11)
    at TCP.onread (net.js:568:26)】
---2017-5-6 13:57:51【error: terminating connection due to administrator command
    at Connection.parseE (E:\develop\workspaces\develop1.9.0\node_modules\pg\lib\connection.js:539:11)
    at Connection.parseMessage (E:\develop\workspaces\develop1.9.0\node_modules\pg\lib\connection.js:366:17)
    at Socket.<anonymous> (E:\develop\workspaces\develop1.9.0\node_modules\pg\lib\connection.js:105:22)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
    at TCP.onread (net.js:547:20)】
---2017-5-6 13:57:51【Error: read ECONNRESET
    at exports._errnoException (util.js:1018:11)
    at TCP.onread (net.js:568:26)】
---2017-5-6 13:57:51【error: terminating connection due to administrator command
    at Connection.parseE (E:\develop\workspaces\develop1.9.0\node_modules\pg\lib\connection.js:539:11)
    at Connection.parseMessage (E:\develop\workspaces\develop1.9.0\node_modules\pg\lib\connection.js:366:17)
    at Socket.<anonymous> (E:\develop\workspaces\develop1.9.0\node_modules\pg\lib\connection.js:105:22)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
    at TCP.onread (net.js:547:20)】
---2017-5-6 13:57:51【Error: read ECONNRESET
    at exports._errnoException (util.js:1018:11)
    at TCP.onread (net.js:568:26)】
---2017-5-6 13:57:51【error: terminating connection due to administrator command
    at Connection.parseE (E:\develop\workspaces\develop1.9.0\node_modules\pg\lib\connection.js:539:11)
    at Connection.parseMessage (E:\develop\workspaces\develop1.9.0\node_modules\pg\lib\connection.js:366:17)
    at Socket.<anonymous> (E:\develop\workspaces\develop1.9.0\node_modules\pg\lib\connection.js:105:22)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
    at TCP.onread (net.js:547:20)】
---2017-5-6 13:57:51【Error: read ECONNRESET
    at exports._errnoException (util.js:1018:11)
    at TCP.onread (net.js:568:26)】
---2017-5-6 13:58:31【Error: connect ETIMEDOUT 192.168.0.100:5432
    at Object.exports._errnoException (util.js:1018:11)
    at exports._exceptionWithHostPort (util.js:1041:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1086:14)】
---2017-5-6 13:58:31【Error: Connection terminated
    at Connection.<anonymous> (E:\develop\workspaces\develop1.9.0\node_modules\pg\lib\client.js:183:17)
    at Connection.g (events.js:292:16)
    at emitNone (events.js:86:13)
    at Connection.emit (events.js:185:7)
    at Socket.<anonymous> (E:\develop\workspaces\develop1.9.0\node_modules\pg\lib\connection.js:66:10)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at TCP._handle.close [as _onclose] (net.js:497:12)】
---2017-5-6 13:58:32【Error: connect ETIMEDOUT 192.168.0.100:5432
    at Object.exports._errnoException (util.js:1018:11)
    at exports._exceptionWithHostPort (util.js:1041:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1086:14)】
---2017-5-6 13:58:32【Error: connect ETIMEDOUT 192.168.0.100:5432
    at Object.exports._errnoException (util.js:1018:11)
    at exports._exceptionWithHostPort (util.js:1041:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1086:14)】
---2017-5-6 13:58:32【Error: Connection terminated
    at Connection.<anonymous> (E:\develop\workspaces\develop1.9.0\node_modules\pg\lib\client.js:183:17)
    at Connection.g (events.js:292:16)
    at emitNone (events.js:86:13)
    at Connection.emit (events.js:185:7)
    at Socket.<anonymous> (E:\develop\workspaces\develop1.9.0\node_modules\pg\lib\connection.js:66:10)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at TCP._handle.close [as _onclose] (net.js:497:12)】
---2017-5-6 13:58:32【Error: Connection terminated
    at Connection.<anonymous> (E:\develop\workspaces\develop1.9.0\node_modules\pg\lib\client.js:183:17)
    at Connection.g (events.js:292:16)
    at emitNone (events.js:86:13)
    at Connection.emit (events.js:185:7)
    at Socket.<anonymous> (E:\develop\workspaces\develop1.9.0\node_modules\pg\lib\connection.js:66:10)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at TCP._handle.close [as _onclose] (net.js:497:12)】
---2017-5-6 13:58:32【Error: connect ETIMEDOUT 192.168.0.100:5432
    at Object.exports._errnoException (util.js:1018:11)
    at exports._exceptionWithHostPort (util.js:1041:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1086:14)】
---2017-5-6 13:58:32【Error: Connection terminated
    at Connection.<anonymous> (E:\develop\workspaces\develop1.9.0\node_modules\pg\lib\client.js:183:17)
    at Connection.g (events.js:292:16)
    at emitNone (events.js:86:13)
    at Connection.emit (events.js:185:7)
    at Socket.<anonymous> (E:\develop\workspaces\develop1.9.0\node_modules\pg\lib\connection.js:66:10)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at TCP._handle.close [as _onclose] (net.js:497:12)】
---2017-5-6 13:58:33【Error: connect ETIMEDOUT 192.168.0.100:5432
    at Object.exports._errnoException (util.js:1018:11)
    at exports._exceptionWithHostPort (util.js:1041:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1086:14)】
---2017-5-6 13:58:33【Error: Connection terminated
    at Connection.<anonymous> (E:\develop\workspaces\develop1.9.0\node_modules\pg\lib\client.js:183:17)
    at Connection.g (events.js:292:16)
    at emitNone (events.js:86:13)
    at Connection.emit (events.js:185:7)
    at Socket.<anonymous> (E:\develop\workspaces\develop1.9.0\node_modules\pg\lib\connection.js:66:10)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at TCP._handle.close [as _onclose] (net.js:497:12)】
---2017-5-6 13:58:34【Error: connect ETIMEDOUT 192.168.0.100:5432
    at Object.exports._errnoException (util.js:1018:11)
    at exports._exceptionWithHostPort (util.js:1041:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1086:14)】
---2017-5-6 13:58:34【Error: Connection terminated
    at Connection.<anonymous> (E:\develop\workspaces\develop1.9.0\node_modules\pg\lib\client.js:183:17)
    at Connection.g (events.js:292:16)
    at emitNone (events.js:86:13)
    at Connection.emit (events.js:185:7)
    at Socket.<anonymous> (E:\develop\workspaces\develop1.9.0\node_modules\pg\lib\connection.js:66:10)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at TCP._handle.close [as _onclose] (net.js:497:12)】
---2017-5-6 13:58:34【Error: connect ETIMEDOUT 192.168.0.100:5432
    at Object.exports._errnoException (util.js:1018:11)
    at exports._exceptionWithHostPort (util.js:1041:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1086:14)】
---2017-5-6 13:58:34【Error: Connection terminated
    at Connection.<anonymous> (E:\develop\workspaces\develop1.9.0\node_modules\pg\lib\client.js:183:17)
    at Connection.g (events.js:292:16)
    at emitNone (events.js:86:13)
    at Connection.emit (events.js:185:7)
    at Socket.<anonymous> (E:\develop\workspaces\develop1.9.0\node_modules\pg\lib\connection.js:66:10)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at TCP._handle.close [as _onclose] (net.js:497:12)】
---2017-5-6 13:58:35【Error: connect ETIMEDOUT 192.168.0.100:5432
    at Object.exports._errnoException (util.js:1018:11)
    at exports._exceptionWithHostPort (util.js:1041:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1086:14)】
---2017-5-6 13:58:35【Error: Connection terminated
    at Connection.<anonymous> (E:\develop\workspaces\develop1.9.0\node_modules\pg\lib\client.js:183:17)
    at Connection.g (events.js:292:16)
    at emitNone (events.js:86:13)
    at Connection.emit (events.js:185:7)
    at Socket.<anonymous> (E:\develop\workspaces\develop1.9.0\node_modules\pg\lib\connection.js:66:10)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at TCP._handle.close [as _onclose] (net.js:497:12)】
---2017-5-6 13:58:36【Error: connect ETIMEDOUT 192.168.0.100:5432
    at Object.exports._errnoException (util.js:1018:11)
    at exports._exceptionWithHostPort (util.js:1041:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1086:14)】
---2017-5-6 13:58:36【Error: Connection terminated
    at Connection.<anonymous> (E:\develop\workspaces\develop1.9.0\node_modules\pg\lib\client.js:183:17)
    at Connection.g (events.js:292:16)
    at emitNone (events.js:86:13)
    at Connection.emit (events.js:185:7)
    at Socket.<anonymous> (E:\develop\workspaces\develop1.9.0\node_modules\pg\lib\connection.js:66:10)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at TCP._handle.close [as _onclose] (net.js:497:12)】
---2017-5-6 13:58:38【Error: connect ETIMEDOUT 192.168.0.100:5432
    at Object.exports._errnoException (util.js:1018:11)
    at exports._exceptionWithHostPort (util.js:1041:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1086:14)】
---2017-5-6 13:58:38【Error: Connection terminated
    at Connection.<anonymous> (E:\develop\workspaces\develop1.9.0\node_modules\pg\lib\client.js:183:17)
    at Connection.g (events.js:292:16)
    at emitNone (events.js:86:13)
    at Connection.emit (events.js:185:7)
    at Socket.<anonymous> (E:\develop\workspaces\develop1.9.0\node_modules\pg\lib\connection.js:66:10)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at TCP._handle.close [as _onclose] (net.js:497:12)】
---2017-5-6 14:15:3【TypeError: Cannot read property '收款金额' of undefined
    at Object.module.exports.run (E:\develop\workspaces\develop1.9.0\ajax\transfer_return_alipay.js:110:47)
    at E:\develop\workspaces\develop1.9.0\ajax\ajax.js:27:20】
---2017-5-6 14:31:5【TypeError: Cannot read property 'merNo' of null
    at Object.module.exports.run (E:\develop\workspaces\develop1.9.0\ajax\transfer_return_alipay.js:63:29)
    at E:\develop\workspaces\develop1.9.0\ajax\ajax.js:27:20】
---2017-5-6 15:57:18【Error: connect ETIMEDOUT 192.168.0.100:5432
    at Object.exports._errnoException (util.js:1018:11)
    at exports._exceptionWithHostPort (util.js:1041:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1086:14)】
---2017-5-6 15:57:18【Error: Connection terminated
    at Connection.<anonymous> (E:\develop\workspaces\develop1.9.0\node_modules\pg\lib\client.js:183:17)
    at Connection.g (events.js:292:16)
    at emitNone (events.js:86:13)
    at Connection.emit (events.js:185:7)
    at Socket.<anonymous> (E:\develop\workspaces\develop1.9.0\node_modules\pg\lib\connection.js:66:10)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at TCP._handle.close [as _onclose] (net.js:497:12)】
---2017-5-6 15:57:26【Error: connect ETIMEDOUT 192.168.0.100:5432
    at Object.exports._errnoException (util.js:1018:11)
    at exports._exceptionWithHostPort (util.js:1041:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1086:14)】
---2017-5-6 15:57:26【Error: Connection terminated
    at Connection.<anonymous> (E:\develop\workspaces\develop1.9.0\node_modules\pg\lib\client.js:183:17)
    at Connection.g (events.js:292:16)
    at emitNone (events.js:86:13)
    at Connection.emit (events.js:185:7)
    at Socket.<anonymous> (E:\develop\workspaces\develop1.9.0\node_modules\pg\lib\connection.js:66:10)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at TCP._handle.close [as _onclose] (net.js:497:12)】
---2017-5-6 15:57:26【Error: connect ETIMEDOUT 192.168.0.100:5432
    at Object.exports._errnoException (util.js:1018:11)
    at exports._exceptionWithHostPort (util.js:1041:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1086:14)】
---2017-5-6 15:57:26【Error: Connection terminated
    at Connection.<anonymous> (E:\develop\workspaces\develop1.9.0\node_modules\pg\lib\client.js:183:17)
    at Connection.g (events.js:292:16)
    at emitNone (events.js:86:13)
    at Connection.emit (events.js:185:7)
    at Socket.<anonymous> (E:\develop\workspaces\develop1.9.0\node_modules\pg\lib\connection.js:66:10)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at TCP._handle.close [as _onclose] (net.js:497:12)】
---2017-5-6 16:0:23【Error: connect ETIMEDOUT 192.168.0.100:5432
    at Object.exports._errnoException (util.js:1018:11)
    at exports._exceptionWithHostPort (util.js:1041:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1086:14)】
---2017-5-6 16:0:23【Error: Connection terminated
    at Connection.<anonymous> (E:\develop\workspaces\develop1.9.0\node_modules\pg\lib\client.js:183:17)
    at Connection.g (events.js:292:16)
    at emitNone (events.js:86:13)
    at Connection.emit (events.js:185:7)
    at Socket.<anonymous> (E:\develop\workspaces\develop1.9.0\node_modules\pg\lib\connection.js:66:10)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at TCP._handle.close [as _onclose] (net.js:497:12)】
---2017-5-6 16:0:23【Error: connect ETIMEDOUT 192.168.0.100:5432
    at Object.exports._errnoException (util.js:1018:11)
    at exports._exceptionWithHostPort (util.js:1041:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1086:14)】
---2017-5-6 16:0:23【Error: connect ETIMEDOUT 192.168.0.100:5432
    at Object.exports._errnoException (util.js:1018:11)
    at exports._exceptionWithHostPort (util.js:1041:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1086:14)】
---2017-5-6 16:0:23【Error: connect ETIMEDOUT 192.168.0.100:5432
    at Object.exports._errnoException (util.js:1018:11)
    at exports._exceptionWithHostPort (util.js:1041:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1086:14)】
---2017-5-6 16:0:23【Error: connect ETIMEDOUT 192.168.0.100:5432
    at Object.exports._errnoException (util.js:1018:11)
    at exports._exceptionWithHostPort (util.js:1041:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1086:14)】
---2017-5-6 16:0:23【Error: Connection terminated
    at Connection.<anonymous> (E:\develop\workspaces\develop1.9.0\node_modules\pg\lib\client.js:183:17)
    at Connection.g (events.js:292:16)
    at emitNone (events.js:86:13)
    at Connection.emit (events.js:185:7)
    at Socket.<anonymous> (E:\develop\workspaces\develop1.9.0\node_modules\pg\lib\connection.js:66:10)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at TCP._handle.close [as _onclose] (net.js:497:12)】
---2017-5-6 16:0:23【Error: Connection terminated
    at Connection.<anonymous> (E:\develop\workspaces\develop1.9.0\node_modules\pg\lib\client.js:183:17)
    at Connection.g (events.js:292:16)
    at emitNone (events.js:86:13)
    at Connection.emit (events.js:185:7)
    at Socket.<anonymous> (E:\develop\workspaces\develop1.9.0\node_modules\pg\lib\connection.js:66:10)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at TCP._handle.close [as _onclose] (net.js:497:12)】
---2017-5-6 16:0:23【Error: Connection terminated
    at Connection.<anonymous> (E:\develop\workspaces\develop1.9.0\node_modules\pg\lib\client.js:183:17)
    at Connection.g (events.js:292:16)
    at emitNone (events.js:86:13)
    at Connection.emit (events.js:185:7)
    at Socket.<anonymous> (E:\develop\workspaces\develop1.9.0\node_modules\pg\lib\connection.js:66:10)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at TCP._handle.close [as _onclose] (net.js:497:12)】
---2017-5-6 16:0:23【Error: Connection terminated
    at Connection.<anonymous> (E:\develop\workspaces\develop1.9.0\node_modules\pg\lib\client.js:183:17)
    at Connection.g (events.js:292:16)
    at emitNone (events.js:86:13)
    at Connection.emit (events.js:185:7)
    at Socket.<anonymous> (E:\develop\workspaces\develop1.9.0\node_modules\pg\lib\connection.js:66:10)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at TCP._handle.close [as _onclose] (net.js:497:12)】
---2017-5-6 16:1:31【Error: connect ETIMEDOUT 192.168.0.100:5432
    at Object.exports._errnoException (util.js:1018:11)
    at exports._exceptionWithHostPort (util.js:1041:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1086:14)】
---2017-5-6 16:1:31【Error: Connection terminated
    at Connection.<anonymous> (E:\develop\workspaces\develop1.9.0\node_modules\pg\lib\client.js:183:17)
    at Connection.g (events.js:292:16)
    at emitNone (events.js:86:13)
    at Connection.emit (events.js:185:7)
    at Socket.<anonymous> (E:\develop\workspaces\develop1.9.0\node_modules\pg\lib\connection.js:66:10)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at TCP._handle.close [as _onclose] (net.js:497:12)】
---2017-5-6 16:2:10【Error: connect ETIMEDOUT 192.168.0.100:5432
    at Object.exports._errnoException (util.js:1018:11)
    at exports._exceptionWithHostPort (util.js:1041:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1086:14)】
---2017-5-6 16:2:10【Error: Connection terminated
    at Connection.<anonymous> (E:\develop\workspaces\develop1.9.0\node_modules\pg\lib\client.js:183:17)
    at Connection.g (events.js:292:16)
    at emitNone (events.js:86:13)
    at Connection.emit (events.js:185:7)
    at Socket.<anonymous> (E:\develop\workspaces\develop1.9.0\node_modules\pg\lib\connection.js:66:10)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at TCP._handle.close [as _onclose] (net.js:497:12)】
---2017-5-6 16:2:10【Error: connect ETIMEDOUT 192.168.0.100:5432
    at Object.exports._errnoException (util.js:1018:11)
    at exports._exceptionWithHostPort (util.js:1041:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1086:14)】
---2017-5-6 16:2:10【Error: Connection terminated
    at Connection.<anonymous> (E:\develop\workspaces\develop1.9.0\node_modules\pg\lib\client.js:183:17)
    at Connection.g (events.js:292:16)
    at emitNone (events.js:86:13)
    at Connection.emit (events.js:185:7)
    at Socket.<anonymous> (E:\develop\workspaces\develop1.9.0\node_modules\pg\lib\connection.js:66:10)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at TCP._handle.close [as _onclose] (net.js:497:12)】
---2017-5-6 16:2:10【Error: connect ETIMEDOUT 192.168.0.100:5432
    at Object.exports._errnoException (util.js:1018:11)
    at exports._exceptionWithHostPort (util.js:1041:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1086:14)】
---2017-5-6 16:2:10【Error: connect ETIMEDOUT 192.168.0.100:5432
    at Object.exports._errnoException (util.js:1018:11)
    at exports._exceptionWithHostPort (util.js:1041:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1086:14)】
---2017-5-6 16:2:10【Error: Connection terminated
    at Connection.<anonymous> (E:\develop\workspaces\develop1.9.0\node_modules\pg\lib\client.js:183:17)
    at Connection.g (events.js:292:16)
    at emitNone (events.js:86:13)
    at Connection.emit (events.js:185:7)
    at Socket.<anonymous> (E:\develop\workspaces\develop1.9.0\node_modules\pg\lib\connection.js:66:10)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at TCP._handle.close [as _onclose] (net.js:497:12)】
---2017-5-6 16:2:10【Error: Connection terminated
    at Connection.<anonymous> (E:\develop\workspaces\develop1.9.0\node_modules\pg\lib\client.js:183:17)
    at Connection.g (events.js:292:16)
    at emitNone (events.js:86:13)
    at Connection.emit (events.js:185:7)
    at Socket.<anonymous> (E:\develop\workspaces\develop1.9.0\node_modules\pg\lib\connection.js:66:10)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at TCP._handle.close [as _onclose] (net.js:497:12)】
---2017-5-6 16:2:28【Error: connect ETIMEDOUT 192.168.0.100:5432
    at Object.exports._errnoException (util.js:1018:11)
    at exports._exceptionWithHostPort (util.js:1041:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1086:14)】
---2017-5-6 16:2:28【Error: connect ETIMEDOUT 192.168.0.100:5432
    at Object.exports._errnoException (util.js:1018:11)
    at exports._exceptionWithHostPort (util.js:1041:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1086:14)】
---2017-5-6 16:2:28【Error: Connection terminated
    at Connection.<anonymous> (E:\develop\workspaces\develop1.9.0\node_modules\pg\lib\client.js:183:17)
    at Connection.g (events.js:292:16)
    at emitNone (events.js:86:13)
    at Connection.emit (events.js:185:7)
    at Socket.<anonymous> (E:\develop\workspaces\develop1.9.0\node_modules\pg\lib\connection.js:66:10)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at TCP._handle.close [as _onclose] (net.js:497:12)】
---2017-5-6 16:2:28【Error: Connection terminated
    at Connection.<anonymous> (E:\develop\workspaces\develop1.9.0\node_modules\pg\lib\client.js:183:17)
    at Connection.g (events.js:292:16)
    at emitNone (events.js:86:13)
    at Connection.emit (events.js:185:7)
    at Socket.<anonymous> (E:\develop\workspaces\develop1.9.0\node_modules\pg\lib\connection.js:66:10)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at TCP._handle.close [as _onclose] (net.js:497:12)】
---2017-5-6 16:2:41【Error: connect ETIMEDOUT 192.168.0.100:5432
    at Object.exports._errnoException (util.js:1018:11)
    at exports._exceptionWithHostPort (util.js:1041:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1086:14)】
---2017-5-6 16:2:41【Error: Connection terminated
    at Connection.<anonymous> (E:\develop\workspaces\develop1.9.0\node_modules\pg\lib\client.js:183:17)
    at Connection.g (events.js:292:16)
    at emitNone (events.js:86:13)
    at Connection.emit (events.js:185:7)
    at Socket.<anonymous> (E:\develop\workspaces\develop1.9.0\node_modules\pg\lib\connection.js:66:10)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at TCP._handle.close [as _onclose] (net.js:497:12)】
---2017-5-6 16:3:13【Error: connect ETIMEDOUT 192.168.0.100:5432
    at Object.exports._errnoException (util.js:1018:11)
    at exports._exceptionWithHostPort (util.js:1041:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1086:14)】
---2017-5-6 16:3:13【Error: connect ETIMEDOUT 192.168.0.100:5432
    at Object.exports._errnoException (util.js:1018:11)
    at exports._exceptionWithHostPort (util.js:1041:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1086:14)】
---2017-5-6 16:3:13【Error: connect ETIMEDOUT 192.168.0.100:5432
    at Object.exports._errnoException (util.js:1018:11)
    at exports._exceptionWithHostPort (util.js:1041:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1086:14)】
---2017-5-6 16:3:13【Error: Connection terminated
    at Connection.<anonymous> (E:\develop\workspaces\develop1.9.0\node_modules\pg\lib\client.js:183:17)
    at Connection.g (events.js:292:16)
    at emitNone (events.js:86:13)
    at Connection.emit (events.js:185:7)
    at Socket.<anonymous> (E:\develop\workspaces\develop1.9.0\node_modules\pg\lib\connection.js:66:10)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at TCP._handle.close [as _onclose] (net.js:497:12)】
---2017-5-6 16:3:13【Error: Connection terminated
    at Connection.<anonymous> (E:\develop\workspaces\develop1.9.0\node_modules\pg\lib\client.js:183:17)
    at Connection.g (events.js:292:16)
    at emitNone (events.js:86:13)
    at Connection.emit (events.js:185:7)
    at Socket.<anonymous> (E:\develop\workspaces\develop1.9.0\node_modules\pg\lib\connection.js:66:10)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at TCP._handle.close [as _onclose] (net.js:497:12)】
---2017-5-6 16:3:13【Error: Connection terminated
    at Connection.<anonymous> (E:\develop\workspaces\develop1.9.0\node_modules\pg\lib\client.js:183:17)
    at Connection.g (events.js:292:16)
    at emitNone (events.js:86:13)
    at Connection.emit (events.js:185:7)
    at Socket.<anonymous> (E:\develop\workspaces\develop1.9.0\node_modules\pg\lib\connection.js:66:10)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at TCP._handle.close [as _onclose] (net.js:497:12)】
---2017-5-6 16:3:13【Error: connect ETIMEDOUT 192.168.0.100:5432
    at Object.exports._errnoException (util.js:1018:11)
    at exports._exceptionWithHostPort (util.js:1041:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1086:14)】
---2017-5-6 16:3:13【Error: connect ETIMEDOUT 192.168.0.100:5432
    at Object.exports._errnoException (util.js:1018:11)
    at exports._exceptionWithHostPort (util.js:1041:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1086:14)】
---2017-5-6 16:3:13【Error: Connection terminated
    at Connection.<anonymous> (E:\develop\workspaces\develop1.9.0\node_modules\pg\lib\client.js:183:17)
    at Connection.g (events.js:292:16)
    at emitNone (events.js:86:13)
    at Connection.emit (events.js:185:7)
    at Socket.<anonymous> (E:\develop\workspaces\develop1.9.0\node_modules\pg\lib\connection.js:66:10)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at TCP._handle.close [as _onclose] (net.js:497:12)】
---2017-5-6 16:3:13【Error: Connection terminated
    at Connection.<anonymous> (E:\develop\workspaces\develop1.9.0\node_modules\pg\lib\client.js:183:17)
    at Connection.g (events.js:292:16)
    at emitNone (events.js:86:13)
    at Connection.emit (events.js:185:7)
    at Socket.<anonymous> (E:\develop\workspaces\develop1.9.0\node_modules\pg\lib\connection.js:66:10)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at TCP._handle.close [as _onclose] (net.js:497:12)】
---2017-5-6 16:3:13【Error: connect ETIMEDOUT 192.168.0.100:5432
    at Object.exports._errnoException (util.js:1018:11)
    at exports._exceptionWithHostPort (util.js:1041:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1086:14)】
---2017-5-6 16:3:13【Error: connect ETIMEDOUT 192.168.0.100:5432
    at Object.exports._errnoException (util.js:1018:11)
    at exports._exceptionWithHostPort (util.js:1041:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1086:14)】
---2017-5-6 16:3:13【Error: Connection terminated
    at Connection.<anonymous> (E:\develop\workspaces\develop1.9.0\node_modules\pg\lib\client.js:183:17)
    at Connection.g (events.js:292:16)
    at emitNone (events.js:86:13)
    at Connection.emit (events.js:185:7)
    at Socket.<anonymous> (E:\develop\workspaces\develop1.9.0\node_modules\pg\lib\connection.js:66:10)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at TCP._handle.close [as _onclose] (net.js:497:12)】
---2017-5-6 16:3:13【Error: Connection terminated
    at Connection.<anonymous> (E:\develop\workspaces\develop1.9.0\node_modules\pg\lib\client.js:183:17)
    at Connection.g (events.js:292:16)
    at emitNone (events.js:86:13)
    at Connection.emit (events.js:185:7)
    at Socket.<anonymous> (E:\develop\workspaces\develop1.9.0\node_modules\pg\lib\connection.js:66:10)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at TCP._handle.close [as _onclose] (net.js:497:12)】
---2017-5-6 16:3:16【Error: connect ETIMEDOUT 192.168.0.100:5432
    at Object.exports._errnoException (util.js:1018:11)
    at exports._exceptionWithHostPort (util.js:1041:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1086:14)】
---2017-5-6 16:3:16【Error: Connection terminated
    at Connection.<anonymous> (E:\develop\workspaces\develop1.9.0\node_modules\pg\lib\client.js:183:17)
    at Connection.g (events.js:292:16)
    at emitNone (events.js:86:13)
    at Connection.emit (events.js:185:7)
    at Socket.<anonymous> (E:\develop\workspaces\develop1.9.0\node_modules\pg\lib\connection.js:66:10)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at TCP._handle.close [as _onclose] (net.js:497:12)】
---2017-5-6 16:3:16【Error: connect ETIMEDOUT 192.168.0.100:5432
    at Object.exports._errnoException (util.js:1018:11)
    at exports._exceptionWithHostPort (util.js:1041:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1086:14)】
---2017-5-6 16:3:16【Error: connect ETIMEDOUT 192.168.0.100:5432
    at Object.exports._errnoException (util.js:1018:11)
    at exports._exceptionWithHostPort (util.js:1041:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1086:14)】
---2017-5-6 16:3:16【Error: Connection terminated
    at Connection.<anonymous> (E:\develop\workspaces\develop1.9.0\node_modules\pg\lib\client.js:183:17)
    at Connection.g (events.js:292:16)
    at emitNone (events.js:86:13)
    at Connection.emit (events.js:185:7)
    at Socket.<anonymous> (E:\develop\workspaces\develop1.9.0\node_modules\pg\lib\connection.js:66:10)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at TCP._handle.close [as _onclose] (net.js:497:12)】
---2017-5-6 16:3:16【Error: Connection terminated
    at Connection.<anonymous> (E:\develop\workspaces\develop1.9.0\node_modules\pg\lib\client.js:183:17)
    at Connection.g (events.js:292:16)
    at emitNone (events.js:86:13)
    at Connection.emit (events.js:185:7)
    at Socket.<anonymous> (E:\develop\workspaces\develop1.9.0\node_modules\pg\lib\connection.js:66:10)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at TCP._handle.close [as _onclose] (net.js:497:12)】
---2017-5-6 16:3:18【Error: connect ETIMEDOUT 192.168.0.100:5432
    at Object.exports._errnoException (util.js:1018:11)
    at exports._exceptionWithHostPort (util.js:1041:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1086:14)】
---2017-5-6 16:3:18【Error: Connection terminated
    at Connection.<anonymous> (E:\develop\workspaces\develop1.9.0\node_modules\pg\lib\client.js:183:17)
    at Connection.g (events.js:292:16)
    at emitNone (events.js:86:13)
    at Connection.emit (events.js:185:7)
    at Socket.<anonymous> (E:\develop\workspaces\develop1.9.0\node_modules\pg\lib\connection.js:66:10)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at TCP._handle.close [as _onclose] (net.js:497:12)】
---2017-5-6 16:3:18【Error: connect ETIMEDOUT 192.168.0.100:5432
    at Object.exports._errnoException (util.js:1018:11)
    at exports._exceptionWithHostPort (util.js:1041:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1086:14)】
---2017-5-6 16:3:18【Error: Connection terminated
    at Connection.<anonymous> (E:\develop\workspaces\develop1.9.0\node_modules\pg\lib\client.js:183:17)
    at Connection.g (events.js:292:16)
    at emitNone (events.js:86:13)
    at Connection.emit (events.js:185:7)
    at Socket.<anonymous> (E:\develop\workspaces\develop1.9.0\node_modules\pg\lib\connection.js:66:10)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at TCP._handle.close [as _onclose] (net.js:497:12)】
---2017-5-6 16:3:20【Error: connect ETIMEDOUT 192.168.0.100:5432
    at Object.exports._errnoException (util.js:1018:11)
    at exports._exceptionWithHostPort (util.js:1041:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1086:14)】
---2017-5-6 16:3:20【Error: connect ETIMEDOUT 192.168.0.100:5432
    at Object.exports._errnoException (util.js:1018:11)
    at exports._exceptionWithHostPort (util.js:1041:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1086:14)】
---2017-5-6 16:3:20【Error: connect ETIMEDOUT 192.168.0.100:5432
    at Object.exports._errnoException (util.js:1018:11)
    at exports._exceptionWithHostPort (util.js:1041:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1086:14)】
---2017-5-6 16:3:20【Error: Connection terminated
    at Connection.<anonymous> (E:\develop\workspaces\develop1.9.0\node_modules\pg\lib\client.js:183:17)
    at Connection.g (events.js:292:16)
    at emitNone (events.js:86:13)
    at Connection.emit (events.js:185:7)
    at Socket.<anonymous> (E:\develop\workspaces\develop1.9.0\node_modules\pg\lib\connection.js:66:10)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at TCP._handle.close [as _onclose] (net.js:497:12)】
---2017-5-6 16:3:20【Error: Connection terminated
    at Connection.<anonymous> (E:\develop\workspaces\develop1.9.0\node_modules\pg\lib\client.js:183:17)
    at Connection.g (events.js:292:16)
    at emitNone (events.js:86:13)
    at Connection.emit (events.js:185:7)
    at Socket.<anonymous> (E:\develop\workspaces\develop1.9.0\node_modules\pg\lib\connection.js:66:10)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at TCP._handle.close [as _onclose] (net.js:497:12)】
---2017-5-6 16:3:20【Error: Connection terminated
    at Connection.<anonymous> (E:\develop\workspaces\develop1.9.0\node_modules\pg\lib\client.js:183:17)
    at Connection.g (events.js:292:16)
    at emitNone (events.js:86:13)
    at Connection.emit (events.js:185:7)
    at Socket.<anonymous> (E:\develop\workspaces\develop1.9.0\node_modules\pg\lib\connection.js:66:10)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at TCP._handle.close [as _onclose] (net.js:497:12)】
---2017-5-6 16:4:17【Error: connect ETIMEDOUT 192.168.0.100:5432
    at Object.exports._errnoException (util.js:1018:11)
    at exports._exceptionWithHostPort (util.js:1041:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1086:14)】
---2017-5-6 16:4:17【Error: connect ETIMEDOUT 192.168.0.100:5432
    at Object.exports._errnoException (util.js:1018:11)
    at exports._exceptionWithHostPort (util.js:1041:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1086:14)】
---2017-5-6 16:4:17【Error: connect ETIMEDOUT 192.168.0.100:5432
    at Object.exports._errnoException (util.js:1018:11)
    at exports._exceptionWithHostPort (util.js:1041:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1086:14)】
---2017-5-6 16:4:17【Error: connect ETIMEDOUT 192.168.0.100:5432
    at Object.exports._errnoException (util.js:1018:11)
    at exports._exceptionWithHostPort (util.js:1041:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1086:14)】
---2017-5-6 16:4:17【Error: connect ETIMEDOUT 192.168.0.100:5432
    at Object.exports._errnoException (util.js:1018:11)
    at exports._exceptionWithHostPort (util.js:1041:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1086:14)】
---2017-5-6 16:4:17【Error: Connection terminated
    at Connection.<anonymous> (E:\develop\workspaces\develop1.9.0\node_modules\pg\lib\client.js:183:17)
    at Connection.g (events.js:292:16)
    at emitNone (events.js:86:13)
    at Connection.emit (events.js:185:7)
    at Socket.<anonymous> (E:\develop\workspaces\develop1.9.0\node_modules\pg\lib\connection.js:66:10)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at TCP._handle.close [as _onclose] (net.js:497:12)】
---2017-5-6 16:4:17【Error: Connection terminated
    at Connection.<anonymous> (E:\develop\workspaces\develop1.9.0\node_modules\pg\lib\client.js:183:17)
    at Connection.g (events.js:292:16)
    at emitNone (events.js:86:13)
    at Connection.emit (events.js:185:7)
    at Socket.<anonymous> (E:\develop\workspaces\develop1.9.0\node_modules\pg\lib\connection.js:66:10)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at TCP._handle.close [as _onclose] (net.js:497:12)】
---2017-5-6 16:4:17【Error: Connection terminated
    at Connection.<anonymous> (E:\develop\workspaces\develop1.9.0\node_modules\pg\lib\client.js:183:17)
    at Connection.g (events.js:292:16)
    at emitNone (events.js:86:13)
    at Connection.emit (events.js:185:7)
    at Socket.<anonymous> (E:\develop\workspaces\develop1.9.0\node_modules\pg\lib\connection.js:66:10)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at TCP._handle.close [as _onclose] (net.js:497:12)】
---2017-5-6 16:4:17【Error: Connection terminated
    at Connection.<anonymous> (E:\develop\workspaces\develop1.9.0\node_modules\pg\lib\client.js:183:17)
    at Connection.g (events.js:292:16)
    at emitNone (events.js:86:13)
    at Connection.emit (events.js:185:7)
    at Socket.<anonymous> (E:\develop\workspaces\develop1.9.0\node_modules\pg\lib\connection.js:66:10)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at TCP._handle.close [as _onclose] (net.js:497:12)】
---2017-5-6 16:4:17【Error: Connection terminated
    at Connection.<anonymous> (E:\develop\workspaces\develop1.9.0\node_modules\pg\lib\client.js:183:17)
    at Connection.g (events.js:292:16)
    at emitNone (events.js:86:13)
    at Connection.emit (events.js:185:7)
    at Socket.<anonymous> (E:\develop\workspaces\develop1.9.0\node_modules\pg\lib\connection.js:66:10)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at TCP._handle.close [as _onclose] (net.js:497:12)】
---2017-5-6 16:4:17【Error: connect ETIMEDOUT 192.168.0.100:5432
    at Object.exports._errnoException (util.js:1018:11)
    at exports._exceptionWithHostPort (util.js:1041:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1086:14)】
---2017-5-6 16:4:17【Error: connect ETIMEDOUT 192.168.0.100:5432
    at Object.exports._errnoException (util.js:1018:11)
    at exports._exceptionWithHostPort (util.js:1041:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1086:14)】
---2017-5-6 16:4:17【Error: connect ETIMEDOUT 192.168.0.100:5432
    at Object.exports._errnoException (util.js:1018:11)
    at exports._exceptionWithHostPort (util.js:1041:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1086:14)】
---2017-5-6 16:4:17【Error: connect ETIMEDOUT 192.168.0.100:5432
    at Object.exports._errnoException (util.js:1018:11)
    at exports._exceptionWithHostPort (util.js:1041:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1086:14)】
---2017-5-6 16:4:17【Error: connect ETIMEDOUT 192.168.0.100:5432
    at Object.exports._errnoException (util.js:1018:11)
    at exports._exceptionWithHostPort (util.js:1041:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1086:14)】
---2017-5-6 16:4:17【Error: Connection terminated
    at Connection.<anonymous> (E:\develop\workspaces\develop1.9.0\node_modules\pg\lib\client.js:183:17)
    at Connection.g (events.js:292:16)
    at emitNone (events.js:86:13)
    at Connection.emit (events.js:185:7)
    at Socket.<anonymous> (E:\develop\workspaces\develop1.9.0\node_modules\pg\lib\connection.js:66:10)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at TCP._handle.close [as _onclose] (net.js:497:12)】
---2017-5-6 16:4:17【Error: Connection terminated
    at Connection.<anonymous> (E:\develop\workspaces\develop1.9.0\node_modules\pg\lib\client.js:183:17)
    at Connection.g (events.js:292:16)
    at emitNone (events.js:86:13)
    at Connection.emit (events.js:185:7)
    at Socket.<anonymous> (E:\develop\workspaces\develop1.9.0\node_modules\pg\lib\connection.js:66:10)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at TCP._handle.close [as _onclose] (net.js:497:12)】
---2017-5-6 16:4:17【Error: Connection terminated
    at Connection.<anonymous> (E:\develop\workspaces\develop1.9.0\node_modules\pg\lib\client.js:183:17)
    at Connection.g (events.js:292:16)
    at emitNone (events.js:86:13)
    at Connection.emit (events.js:185:7)
    at Socket.<anonymous> (E:\develop\workspaces\develop1.9.0\node_modules\pg\lib\connection.js:66:10)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at TCP._handle.close [as _onclose] (net.js:497:12)】
---2017-5-6 16:4:17【Error: Connection terminated
    at Connection.<anonymous> (E:\develop\workspaces\develop1.9.0\node_modules\pg\lib\client.js:183:17)
    at Connection.g (events.js:292:16)
    at emitNone (events.js:86:13)
    at Connection.emit (events.js:185:7)
    at Socket.<anonymous> (E:\develop\workspaces\develop1.9.0\node_modules\pg\lib\connection.js:66:10)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at TCP._handle.close [as _onclose] (net.js:497:12)】
---2017-5-6 16:4:17【Error: Connection terminated
    at Connection.<anonymous> (E:\develop\workspaces\develop1.9.0\node_modules\pg\lib\client.js:183:17)
    at Connection.g (events.js:292:16)
    at emitNone (events.js:86:13)
    at Connection.emit (events.js:185:7)
    at Socket.<anonymous> (E:\develop\workspaces\develop1.9.0\node_modules\pg\lib\connection.js:66:10)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at TCP._handle.close [as _onclose] (net.js:497:12)】
---2017-5-6 16:5:5【Error: connect ETIMEDOUT 192.168.0.100:5432
    at Object.exports._errnoException (util.js:1018:11)
    at exports._exceptionWithHostPort (util.js:1041:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1086:14)】
---2017-5-6 16:5:5【Error: connect ETIMEDOUT 192.168.0.100:5432
    at Object.exports._errnoException (util.js:1018:11)
    at exports._exceptionWithHostPort (util.js:1041:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1086:14)】
---2017-5-6 16:5:5【Error: connect ETIMEDOUT 192.168.0.100:5432
    at Object.exports._errnoException (util.js:1018:11)
    at exports._exceptionWithHostPort (util.js:1041:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1086:14)】
---2017-5-6 16:5:5【Error: connect ETIMEDOUT 192.168.0.100:5432
    at Object.exports._errnoException (util.js:1018:11)
    at exports._exceptionWithHostPort (util.js:1041:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1086:14)】
---2017-5-6 16:5:5【Error: connect ETIMEDOUT 192.168.0.100:5432
    at Object.exports._errnoException (util.js:1018:11)
    at exports._exceptionWithHostPort (util.js:1041:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1086:14)】
---2017-5-6 16:5:5【Error: connect ETIMEDOUT 192.168.0.100:5432
    at Object.exports._errnoException (util.js:1018:11)
    at exports._exceptionWithHostPort (util.js:1041:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1086:14)】
---2017-5-6 16:5:5【Error: connect ETIMEDOUT 192.168.0.100:5432
    at Object.exports._errnoException (util.js:1018:11)
    at exports._exceptionWithHostPort (util.js:1041:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1086:14)】
---2017-5-6 16:5:5【Error: Connection terminated
    at Connection.<anonymous> (E:\develop\workspaces\develop1.9.0\node_modules\pg\lib\client.js:183:17)
    at Connection.g (events.js:292:16)
    at emitNone (events.js:86:13)
    at Connection.emit (events.js:185:7)
    at Socket.<anonymous> (E:\develop\workspaces\develop1.9.0\node_modules\pg\lib\connection.js:66:10)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at TCP._handle.close [as _onclose] (net.js:497:12)】
---2017-5-6 16:5:5【Error: Connection terminated
    at Connection.<anonymous> (E:\develop\workspaces\develop1.9.0\node_modules\pg\lib\client.js:183:17)
    at Connection.g (events.js:292:16)
    at emitNone (events.js:86:13)
    at Connection.emit (events.js:185:7)
    at Socket.<anonymous> (E:\develop\workspaces\develop1.9.0\node_modules\pg\lib\connection.js:66:10)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at TCP._handle.close [as _onclose] (net.js:497:12)】
---2017-5-6 16:5:5【Error: Connection terminated
    at Connection.<anonymous> (E:\develop\workspaces\develop1.9.0\node_modules\pg\lib\client.js:183:17)
    at Connection.g (events.js:292:16)
    at emitNone (events.js:86:13)
    at Connection.emit (events.js:185:7)
    at Socket.<anonymous> (E:\develop\workspaces\develop1.9.0\node_modules\pg\lib\connection.js:66:10)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at TCP._handle.close [as _onclose] (net.js:497:12)】
---2017-5-6 16:5:5【Error: Connection terminated
    at Connection.<anonymous> (E:\develop\workspaces\develop1.9.0\node_modules\pg\lib\client.js:183:17)
    at Connection.g (events.js:292:16)
    at emitNone (events.js:86:13)
    at Connection.emit (events.js:185:7)
    at Socket.<anonymous> (E:\develop\workspaces\develop1.9.0\node_modules\pg\lib\connection.js:66:10)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at TCP._handle.close [as _onclose] (net.js:497:12)】
---2017-5-6 16:5:5【Error: Connection terminated
    at Connection.<anonymous> (E:\develop\workspaces\develop1.9.0\node_modules\pg\lib\client.js:183:17)
    at Connection.g (events.js:292:16)
    at emitNone (events.js:86:13)
    at Connection.emit (events.js:185:7)
    at Socket.<anonymous> (E:\develop\workspaces\develop1.9.0\node_modules\pg\lib\connection.js:66:10)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at TCP._handle.close [as _onclose] (net.js:497:12)】
---2017-5-6 16:5:5【Error: Connection terminated
    at Connection.<anonymous> (E:\develop\workspaces\develop1.9.0\node_modules\pg\lib\client.js:183:17)
    at Connection.g (events.js:292:16)
    at emitNone (events.js:86:13)
    at Connection.emit (events.js:185:7)
    at Socket.<anonymous> (E:\develop\workspaces\develop1.9.0\node_modules\pg\lib\connection.js:66:10)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at TCP._handle.close [as _onclose] (net.js:497:12)】
---2017-5-6 16:5:5【Error: Connection terminated
    at Connection.<anonymous> (E:\develop\workspaces\develop1.9.0\node_modules\pg\lib\client.js:183:17)
    at Connection.g (events.js:292:16)
    at emitNone (events.js:86:13)
    at Connection.emit (events.js:185:7)
    at Socket.<anonymous> (E:\develop\workspaces\develop1.9.0\node_modules\pg\lib\connection.js:66:10)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at TCP._handle.close [as _onclose] (net.js:497:12)】
---2017-5-6 16:5:5【Error: connect ETIMEDOUT 192.168.0.100:5432
    at Object.exports._errnoException (util.js:1018:11)
    at exports._exceptionWithHostPort (util.js:1041:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1086:14)】
---2017-5-6 16:5:5【Error: connect ETIMEDOUT 192.168.0.100:5432
    at Object.exports._errnoException (util.js:1018:11)
    at exports._exceptionWithHostPort (util.js:1041:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1086:14)】
---2017-5-6 16:5:5【Error: connect ETIMEDOUT 192.168.0.100:5432
    at Object.exports._errnoException (util.js:1018:11)
    at exports._exceptionWithHostPort (util.js:1041:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1086:14)】
---2017-5-6 16:5:5【Error: Connection terminated
    at Connection.<anonymous> (E:\develop\workspaces\develop1.9.0\node_modules\pg\lib\client.js:183:17)
    at Connection.g (events.js:292:16)
    at emitNone (events.js:86:13)
    at Connection.emit (events.js:185:7)
    at Socket.<anonymous> (E:\develop\workspaces\develop1.9.0\node_modules\pg\lib\connection.js:66:10)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at TCP._handle.close [as _onclose] (net.js:497:12)】
---2017-5-6 16:5:5【Error: Connection terminated
    at Connection.<anonymous> (E:\develop\workspaces\develop1.9.0\node_modules\pg\lib\client.js:183:17)
    at Connection.g (events.js:292:16)
    at emitNone (events.js:86:13)
    at Connection.emit (events.js:185:7)
    at Socket.<anonymous> (E:\develop\workspaces\develop1.9.0\node_modules\pg\lib\connection.js:66:10)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at TCP._handle.close [as _onclose] (net.js:497:12)】
---2017-5-6 16:5:5【Error: Connection terminated
    at Connection.<anonymous> (E:\develop\workspaces\develop1.9.0\node_modules\pg\lib\client.js:183:17)
    at Connection.g (events.js:292:16)
    at emitNone (events.js:86:13)
    at Connection.emit (events.js:185:7)
    at Socket.<anonymous> (E:\develop\workspaces\develop1.9.0\node_modules\pg\lib\connection.js:66:10)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at TCP._handle.close [as _onclose] (net.js:497:12)】
---2017-5-6 16:5:6【Error: connect ETIMEDOUT 192.168.0.100:5432
    at Object.exports._errnoException (util.js:1018:11)
    at exports._exceptionWithHostPort (util.js:1041:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1086:14)】
---2017-5-6 16:5:6【Error: connect ETIMEDOUT 192.168.0.100:5432
    at Object.exports._errnoException (util.js:1018:11)
    at exports._exceptionWithHostPort (util.js:1041:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1086:14)】
---2017-5-6 16:5:6【Error: connect ETIMEDOUT 192.168.0.100:5432
    at Object.exports._errnoException (util.js:1018:11)
    at exports._exceptionWithHostPort (util.js:1041:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1086:14)】
---2017-5-6 16:5:6【Error: connect ETIMEDOUT 192.168.0.100:5432
    at Object.exports._errnoException (util.js:1018:11)
    at exports._exceptionWithHostPort (util.js:1041:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1086:14)】
---2017-5-6 16:5:6【Error: connect ETIMEDOUT 192.168.0.100:5432
    at Object.exports._errnoException (util.js:1018:11)
    at exports._exceptionWithHostPort (util.js:1041:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1086:14)】
---2017-5-6 16:5:6【Error: Connection terminated
    at Connection.<anonymous> (E:\develop\workspaces\develop1.9.0\node_modules\pg\lib\client.js:183:17)
    at Connection.g (events.js:292:16)
    at emitNone (events.js:86:13)
    at Connection.emit (events.js:185:7)
    at Socket.<anonymous> (E:\develop\workspaces\develop1.9.0\node_modules\pg\lib\connection.js:66:10)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at TCP._handle.close [as _onclose] (net.js:497:12)】
---2017-5-6 16:5:6【Error: Connection terminated
    at Connection.<anonymous> (E:\develop\workspaces\develop1.9.0\node_modules\pg\lib\client.js:183:17)
    at Connection.g (events.js:292:16)
    at emitNone (events.js:86:13)
    at Connection.emit (events.js:185:7)
    at Socket.<anonymous> (E:\develop\workspaces\develop1.9.0\node_modules\pg\lib\connection.js:66:10)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at TCP._handle.close [as _onclose] (net.js:497:12)】
---2017-5-6 16:5:6【Error: Connection terminated
    at Connection.<anonymous> (E:\develop\workspaces\develop1.9.0\node_modules\pg\lib\client.js:183:17)
    at Connection.g (events.js:292:16)
    at emitNone (events.js:86:13)
    at Connection.emit (events.js:185:7)
    at Socket.<anonymous> (E:\develop\workspaces\develop1.9.0\node_modules\pg\lib\connection.js:66:10)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at TCP._handle.close [as _onclose] (net.js:497:12)】
---2017-5-6 16:5:6【Error: Connection terminated
    at Connection.<anonymous> (E:\develop\workspaces\develop1.9.0\node_modules\pg\lib\client.js:183:17)
    at Connection.g (events.js:292:16)
    at emitNone (events.js:86:13)
    at Connection.emit (events.js:185:7)
    at Socket.<anonymous> (E:\develop\workspaces\develop1.9.0\node_modules\pg\lib\connection.js:66:10)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at TCP._handle.close [as _onclose] (net.js:497:12)】
---2017-5-6 16:5:6【Error: Connection terminated
    at Connection.<anonymous> (E:\develop\workspaces\develop1.9.0\node_modules\pg\lib\client.js:183:17)
    at Connection.g (events.js:292:16)
    at emitNone (events.js:86:13)
    at Connection.emit (events.js:185:7)
    at Socket.<anonymous> (E:\develop\workspaces\develop1.9.0\node_modules\pg\lib\connection.js:66:10)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at TCP._handle.close [as _onclose] (net.js:497:12)】
---2017-5-6 16:5:7【Error: connect ETIMEDOUT 192.168.0.100:5432
    at Object.exports._errnoException (util.js:1018:11)
    at exports._exceptionWithHostPort (util.js:1041:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1086:14)】
---2017-5-6 16:5:7【Error: Connection terminated
    at Connection.<anonymous> (E:\develop\workspaces\develop1.9.0\node_modules\pg\lib\client.js:183:17)
    at Connection.g (events.js:292:16)
    at emitNone (events.js:86:13)
    at Connection.emit (events.js:185:7)
    at Socket.<anonymous> (E:\develop\workspaces\develop1.9.0\node_modules\pg\lib\connection.js:66:10)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at TCP._handle.close [as _onclose] (net.js:497:12)】
---2017-5-6 16:5:7【Error: connect ETIMEDOUT 192.168.0.100:5432
    at Object.exports._errnoException (util.js:1018:11)
    at exports._exceptionWithHostPort (util.js:1041:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1086:14)】
---2017-5-6 16:5:7【Error: connect ETIMEDOUT 192.168.0.100:5432
    at Object.exports._errnoException (util.js:1018:11)
    at exports._exceptionWithHostPort (util.js:1041:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1086:14)】
---2017-5-6 16:5:7【Error: Connection terminated
    at Connection.<anonymous> (E:\develop\workspaces\develop1.9.0\node_modules\pg\lib\client.js:183:17)
    at Connection.g (events.js:292:16)
    at emitNone (events.js:86:13)
    at Connection.emit (events.js:185:7)
    at Socket.<anonymous> (E:\develop\workspaces\develop1.9.0\node_modules\pg\lib\connection.js:66:10)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at TCP._handle.close [as _onclose] (net.js:497:12)】
---2017-5-6 16:5:7【Error: Connection terminated
    at Connection.<anonymous> (E:\develop\workspaces\develop1.9.0\node_modules\pg\lib\client.js:183:17)
    at Connection.g (events.js:292:16)
    at emitNone (events.js:86:13)
    at Connection.emit (events.js:185:7)
    at Socket.<anonymous> (E:\develop\workspaces\develop1.9.0\node_modules\pg\lib\connection.js:66:10)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at TCP._handle.close [as _onclose] (net.js:497:12)】
---2017-5-6 16:12:2【Error: connect ETIMEDOUT 192.168.0.100:5432
    at Object.exports._errnoException (util.js:1018:11)
    at exports._exceptionWithHostPort (util.js:1041:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1086:14)】
---2017-5-6 16:12:2【Error: Connection terminated
    at Connection.<anonymous> (E:\develop\workspaces\develop1.9.0\node_modules\pg\lib\client.js:183:17)
    at Connection.g (events.js:292:16)
    at emitNone (events.js:86:13)
    at Connection.emit (events.js:185:7)
    at Socket.<anonymous> (E:\develop\workspaces\develop1.9.0\node_modules\pg\lib\connection.js:66:10)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at TCP._handle.close [as _onclose] (net.js:497:12)】
---2017-5-6 16:13:54【Error: connect ETIMEDOUT 192.168.0.100:5432
    at Object.exports._errnoException (util.js:1018:11)
    at exports._exceptionWithHostPort (util.js:1041:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1086:14)】
---2017-5-6 16:13:54【Error: connect ETIMEDOUT 192.168.0.100:5432
    at Object.exports._errnoException (util.js:1018:11)
    at exports._exceptionWithHostPort (util.js:1041:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1086:14)】
---2017-5-6 16:13:54【Error: connect ETIMEDOUT 192.168.0.100:5432
    at Object.exports._errnoException (util.js:1018:11)
    at exports._exceptionWithHostPort (util.js:1041:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1086:14)】
---2017-5-6 16:13:54【Error: connect ETIMEDOUT 192.168.0.100:5432
    at Object.exports._errnoException (util.js:1018:11)
    at exports._exceptionWithHostPort (util.js:1041:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1086:14)】
---2017-5-6 16:13:54【Error: connect ETIMEDOUT 192.168.0.100:5432
    at Object.exports._errnoException (util.js:1018:11)
    at exports._exceptionWithHostPort (util.js:1041:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1086:14)】
---2017-5-6 16:13:54【Error: connect ETIMEDOUT 192.168.0.100:5432
    at Object.exports._errnoException (util.js:1018:11)
    at exports._exceptionWithHostPort (util.js:1041:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1086:14)】
---2017-5-6 16:13:54【Error: connect ETIMEDOUT 192.168.0.100:5432
    at Object.exports._errnoException (util.js:1018:11)
    at exports._exceptionWithHostPort (util.js:1041:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1086:14)】
---2017-5-6 16:13:54【Error: Connection terminated
    at Connection.<anonymous> (E:\develop\workspaces\develop1.9.0\node_modules\pg\lib\client.js:183:17)
    at Connection.g (events.js:292:16)
    at emitNone (events.js:86:13)
    at Connection.emit (events.js:185:7)
    at Socket.<anonymous> (E:\develop\workspaces\develop1.9.0\node_modules\pg\lib\connection.js:66:10)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at TCP._handle.close [as _onclose] (net.js:497:12)】
---2017-5-6 16:13:54【Error: Connection terminated
    at Connection.<anonymous> (E:\develop\workspaces\develop1.9.0\node_modules\pg\lib\client.js:183:17)
    at Connection.g (events.js:292:16)
    at emitNone (events.js:86:13)
    at Connection.emit (events.js:185:7)
    at Socket.<anonymous> (E:\develop\workspaces\develop1.9.0\node_modules\pg\lib\connection.js:66:10)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at TCP._handle.close [as _onclose] (net.js:497:12)】
---2017-5-6 16:13:54【Error: Connection terminated
    at Connection.<anonymous> (E:\develop\workspaces\develop1.9.0\node_modules\pg\lib\client.js:183:17)
    at Connection.g (events.js:292:16)
    at emitNone (events.js:86:13)
    at Connection.emit (events.js:185:7)
    at Socket.<anonymous> (E:\develop\workspaces\develop1.9.0\node_modules\pg\lib\connection.js:66:10)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at TCP._handle.close [as _onclose] (net.js:497:12)】
---2017-5-6 16:13:54【Error: Connection terminated
    at Connection.<anonymous> (E:\develop\workspaces\develop1.9.0\node_modules\pg\lib\client.js:183:17)
    at Connection.g (events.js:292:16)
    at emitNone (events.js:86:13)
    at Connection.emit (events.js:185:7)
    at Socket.<anonymous> (E:\develop\workspaces\develop1.9.0\node_modules\pg\lib\connection.js:66:10)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at TCP._handle.close [as _onclose] (net.js:497:12)】
---2017-5-6 16:13:54【Error: Connection terminated
    at Connection.<anonymous> (E:\develop\workspaces\develop1.9.0\node_modules\pg\lib\client.js:183:17)
    at Connection.g (events.js:292:16)
    at emitNone (events.js:86:13)
    at Connection.emit (events.js:185:7)
    at Socket.<anonymous> (E:\develop\workspaces\develop1.9.0\node_modules\pg\lib\connection.js:66:10)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at TCP._handle.close [as _onclose] (net.js:497:12)】
---2017-5-6 16:13:54【Error: Connection terminated
    at Connection.<anonymous> (E:\develop\workspaces\develop1.9.0\node_modules\pg\lib\client.js:183:17)
    at Connection.g (events.js:292:16)
    at emitNone (events.js:86:13)
    at Connection.emit (events.js:185:7)
    at Socket.<anonymous> (E:\develop\workspaces\develop1.9.0\node_modules\pg\lib\connection.js:66:10)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at TCP._handle.close [as _onclose] (net.js:497:12)】
---2017-5-6 16:13:54【Error: Connection terminated
    at Connection.<anonymous> (E:\develop\workspaces\develop1.9.0\node_modules\pg\lib\client.js:183:17)
    at Connection.g (events.js:292:16)
    at emitNone (events.js:86:13)
    at Connection.emit (events.js:185:7)
    at Socket.<anonymous> (E:\develop\workspaces\develop1.9.0\node_modules\pg\lib\connection.js:66:10)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at TCP._handle.close [as _onclose] (net.js:497:12)】
---2017-5-6 16:13:56【Error: connect ETIMEDOUT 192.168.0.100:5432
    at Object.exports._errnoException (util.js:1018:11)
    at exports._exceptionWithHostPort (util.js:1041:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1086:14)】
---2017-5-6 16:13:56【Error: connect ETIMEDOUT 192.168.0.100:5432
    at Object.exports._errnoException (util.js:1018:11)
    at exports._exceptionWithHostPort (util.js:1041:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1086:14)】
---2017-5-6 16:13:56【Error: Connection terminated
    at Connection.<anonymous> (E:\develop\workspaces\develop1.9.0\node_modules\pg\lib\client.js:183:17)
    at Connection.g (events.js:292:16)
    at emitNone (events.js:86:13)
    at Connection.emit (events.js:185:7)
    at Socket.<anonymous> (E:\develop\workspaces\develop1.9.0\node_modules\pg\lib\connection.js:66:10)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at TCP._handle.close [as _onclose] (net.js:497:12)】
---2017-5-6 16:13:56【Error: Connection terminated
    at Connection.<anonymous> (E:\develop\workspaces\develop1.9.0\node_modules\pg\lib\client.js:183:17)
    at Connection.g (events.js:292:16)
    at emitNone (events.js:86:13)
    at Connection.emit (events.js:185:7)
    at Socket.<anonymous> (E:\develop\workspaces\develop1.9.0\node_modules\pg\lib\connection.js:66:10)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at TCP._handle.close [as _onclose] (net.js:497:12)】
---2017-5-6 16:14:6【Error: connect ETIMEDOUT 192.168.0.100:5432
    at Object.exports._errnoException (util.js:1018:11)
    at exports._exceptionWithHostPort (util.js:1041:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1086:14)】
---2017-5-6 16:14:6【Error: Connection terminated
    at Connection.<anonymous> (E:\develop\workspaces\develop1.9.0\node_modules\pg\lib\client.js:183:17)
    at Connection.g (events.js:292:16)
    at emitNone (events.js:86:13)
    at Connection.emit (events.js:185:7)
    at Socket.<anonymous> (E:\develop\workspaces\develop1.9.0\node_modules\pg\lib\connection.js:66:10)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at TCP._handle.close [as _onclose] (net.js:497:12)】
---2017-5-6 16:34:1【Error: Can't set headers after they are sent.
    at ServerResponse.OutgoingMessage.setHeader (_http_outgoing.js:357:11)
    at ServerResponse.header (E:\develop\workspaces\develop1.9.1\node_modules\express\lib\response.js:725:10)
    at ServerResponse.send (E:\develop\workspaces\develop1.9.1\node_modules\express\lib\response.js:170:12)
    at ServerResponse.json (E:\develop\workspaces\develop1.9.1\node_modules\express\lib\response.js:256:15)
    at ServerResponse.send (E:\develop\workspaces\develop1.9.1\node_modules\express\lib\response.js:158:21)
    at E:\develop\workspaces\develop1.9.1\apimain.js:365:10
    at FSReqWrap.oncomplete (fs.js:123:15)】
---2017-5-6 16:38:32【Error: Can't set headers after they are sent.
    at ServerResponse.OutgoingMessage.setHeader (_http_outgoing.js:357:11)
    at ServerResponse.header (E:\develop\workspaces\develop1.9.1\node_modules\express\lib\response.js:725:10)
    at ServerResponse.send (E:\develop\workspaces\develop1.9.1\node_modules\express\lib\response.js:170:12)
    at ServerResponse.json (E:\develop\workspaces\develop1.9.1\node_modules\express\lib\response.js:256:15)
    at ServerResponse.send (E:\develop\workspaces\develop1.9.1\node_modules\express\lib\response.js:158:21)
    at E:\develop\workspaces\develop1.9.1\apimain.js:365:10
    at FSReqWrap.oncomplete (fs.js:123:15)】
---2017-5-6 16:38:32【Error: ENOENT: no such file or directory, open 'E:\develop\workspaces\develop1.9.1\temp\2017050616383265055.png'
    at Error (native)】
---2017-5-6 16:42:55【Error: connect ETIMEDOUT 192.168.0.100:5432
    at Object.exports._errnoException (util.js:1018:11)
    at exports._exceptionWithHostPort (util.js:1041:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1086:14)】
---2017-5-6 16:42:55【Error: Connection terminated
    at Connection.<anonymous> (E:\develop\workspaces\develop1.9.1\node_modules\pg\lib\client.js:183:17)
    at Connection.g (events.js:292:16)
    at emitNone (events.js:86:13)
    at Connection.emit (events.js:185:7)
    at Socket.<anonymous> (E:\develop\workspaces\develop1.9.1\node_modules\pg\lib\connection.js:66:10)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at TCP._handle.close [as _onclose] (net.js:497:12)】
---2017-5-6 16:43:40【error: terminating connection due to administrator command
    at Connection.parseE (E:\develop\workspaces\develop1.9.1\node_modules\pg\lib\connection.js:539:11)
    at Connection.parseMessage (E:\develop\workspaces\develop1.9.1\node_modules\pg\lib\connection.js:366:17)
    at Socket.<anonymous> (E:\develop\workspaces\develop1.9.1\node_modules\pg\lib\connection.js:105:22)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
    at TCP.onread (net.js:547:20)】
---2017-5-6 16:43:42【Error: connect ETIMEDOUT 192.168.0.100:5432
    at Object.exports._errnoException (util.js:1018:11)
    at exports._exceptionWithHostPort (util.js:1041:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1086:14)】
---2017-5-6 16:43:42【Error: Connection terminated
    at Connection.<anonymous> (E:\develop\workspaces\develop1.9.1\node_modules\pg\lib\client.js:183:17)
    at Connection.g (events.js:292:16)
    at emitNone (events.js:86:13)
    at Connection.emit (events.js:185:7)
    at Socket.<anonymous> (E:\develop\workspaces\develop1.9.1\node_modules\pg\lib\connection.js:66:10)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at TCP._handle.close [as _onclose] (net.js:497:12)】
---2017-5-6 16:43:42【Error: connect ETIMEDOUT 192.168.0.100:5432
    at Object.exports._errnoException (util.js:1018:11)
    at exports._exceptionWithHostPort (util.js:1041:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1086:14)】
---2017-5-6 16:43:42【Error: Connection terminated
    at Connection.<anonymous> (E:\develop\workspaces\develop1.9.1\node_modules\pg\lib\client.js:183:17)
    at Connection.g (events.js:292:16)
    at emitNone (events.js:86:13)
    at Connection.emit (events.js:185:7)
    at Socket.<anonymous> (E:\develop\workspaces\develop1.9.1\node_modules\pg\lib\connection.js:66:10)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at TCP._handle.close [as _onclose] (net.js:497:12)】
---2017-5-6 16:43:42【Error: connect ETIMEDOUT 192.168.0.100:5432
    at Object.exports._errnoException (util.js:1018:11)
    at exports._exceptionWithHostPort (util.js:1041:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1086:14)】
---2017-5-6 16:43:42【Error: Connection terminated
    at Connection.<anonymous> (E:\develop\workspaces\develop1.9.1\node_modules\pg\lib\client.js:183:17)
    at Connection.g (events.js:292:16)
    at emitNone (events.js:86:13)
    at Connection.emit (events.js:185:7)
    at Socket.<anonymous> (E:\develop\workspaces\develop1.9.1\node_modules\pg\lib\connection.js:66:10)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at TCP._handle.close [as _onclose] (net.js:497:12)】
---2017-5-6 16:43:47【Error: read ECONNRESET
    at exports._errnoException (util.js:1018:11)
    at TCP.onread (net.js:568:26)】
---2017-5-6 16:43:49【error: the database system is shutting down
    at Connection.parseE (E:\develop\workspaces\develop1.9.1\node_modules\pg\lib\connection.js:539:11)
    at Connection.parseMessage (E:\develop\workspaces\develop1.9.1\node_modules\pg\lib\connection.js:366:17)
    at Socket.<anonymous> (E:\develop\workspaces\develop1.9.1\node_modules\pg\lib\connection.js:105:22)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
    at TCP.onread (net.js:547:20)】
---2017-5-6 16:43:49【Error: read ECONNRESET
    at exports._errnoException (util.js:1018:11)
    at TCP.onread (net.js:568:26)】
---2017-5-6 16:43:49【Error: Connection terminated
    at Connection.<anonymous> (E:\develop\workspaces\develop1.9.1\node_modules\pg\lib\client.js:183:17)
    at Connection.g (events.js:292:16)
    at emitNone (events.js:86:13)
    at Connection.emit (events.js:185:7)
    at Socket.<anonymous> (E:\develop\workspaces\develop1.9.1\node_modules\pg\lib\connection.js:66:10)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at TCP._handle.close [as _onclose] (net.js:497:12)】
---2017-5-6 16:43:49【error: the database system is shutting down
    at Connection.parseE (E:\develop\workspaces\develop1.9.1\node_modules\pg\lib\connection.js:539:11)
    at Connection.parseMessage (E:\develop\workspaces\develop1.9.1\node_modules\pg\lib\connection.js:366:17)
    at Socket.<anonymous> (E:\develop\workspaces\develop1.9.1\node_modules\pg\lib\connection.js:105:22)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
    at TCP.onread (net.js:547:20)】
---2017-5-6 16:43:49【Error: read ECONNRESET
    at exports._errnoException (util.js:1018:11)
    at TCP.onread (net.js:568:26)】
---2017-5-6 16:43:49【Error: Connection terminated
    at Connection.<anonymous> (E:\develop\workspaces\develop1.9.1\node_modules\pg\lib\client.js:183:17)
    at Connection.g (events.js:292:16)
    at emitNone (events.js:86:13)
    at Connection.emit (events.js:185:7)
    at Socket.<anonymous> (E:\develop\workspaces\develop1.9.1\node_modules\pg\lib\connection.js:66:10)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at TCP._handle.close [as _onclose] (net.js:497:12)】
---2017-5-6 16:43:49【error: the database system is shutting down
    at Connection.parseE (E:\develop\workspaces\develop1.9.1\node_modules\pg\lib\connection.js:539:11)
    at Connection.parseMessage (E:\develop\workspaces\develop1.9.1\node_modules\pg\lib\connection.js:366:17)
    at Socket.<anonymous> (E:\develop\workspaces\develop1.9.1\node_modules\pg\lib\connection.js:105:22)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
    at TCP.onread (net.js:547:20)】
---2017-5-6 16:43:49【Error: read ECONNRESET
    at exports._errnoException (util.js:1018:11)
    at TCP.onread (net.js:568:26)】
---2017-5-6 16:43:49【Error: Connection terminated
    at Connection.<anonymous> (E:\develop\workspaces\develop1.9.1\node_modules\pg\lib\client.js:183:17)
    at Connection.g (events.js:292:16)
    at emitNone (events.js:86:13)
    at Connection.emit (events.js:185:7)
    at Socket.<anonymous> (E:\develop\workspaces\develop1.9.1\node_modules\pg\lib\connection.js:66:10)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at TCP._handle.close [as _onclose] (net.js:497:12)】
---2017-5-6 16:43:49【error: the database system is shutting down
    at Connection.parseE (E:\develop\workspaces\develop1.9.1\node_modules\pg\lib\connection.js:539:11)
    at Connection.parseMessage (E:\develop\workspaces\develop1.9.1\node_modules\pg\lib\connection.js:366:17)
    at Socket.<anonymous> (E:\develop\workspaces\develop1.9.1\node_modules\pg\lib\connection.js:105:22)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
    at TCP.onread (net.js:547:20)】
---2017-5-6 16:43:49【Error: read ECONNRESET
    at exports._errnoException (util.js:1018:11)
    at TCP.onread (net.js:568:26)】
---2017-5-6 16:43:49【Error: Connection terminated
    at Connection.<anonymous> (E:\develop\workspaces\develop1.9.1\node_modules\pg\lib\client.js:183:17)
    at Connection.g (events.js:292:16)
    at emitNone (events.js:86:13)
    at Connection.emit (events.js:185:7)
    at Socket.<anonymous> (E:\develop\workspaces\develop1.9.1\node_modules\pg\lib\connection.js:66:10)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at TCP._handle.close [as _onclose] (net.js:497:12)】
---2017-5-6 16:43:51【Error: read ECONNRESET
    at exports._errnoException (util.js:1018:11)
    at TCP.onread (net.js:568:26)】
---2017-5-6 16:43:51【Error: Connection terminated
    at Connection.<anonymous> (E:\develop\workspaces\develop1.9.1\node_modules\pg\lib\client.js:183:17)
    at Connection.g (events.js:292:16)
    at emitNone (events.js:86:13)
    at Connection.emit (events.js:185:7)
    at Socket.<anonymous> (E:\develop\workspaces\develop1.9.1\node_modules\pg\lib\connection.js:66:10)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at TCP._handle.close [as _onclose] (net.js:497:12)】
---2017-5-6 16:43:57【Error: connect ETIMEDOUT 192.168.0.100:5432
    at Object.exports._errnoException (util.js:1018:11)
    at exports._exceptionWithHostPort (util.js:1041:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1086:14)】
---2017-5-6 16:43:57【Error: connect ETIMEDOUT 192.168.0.100:5432
    at Object.exports._errnoException (util.js:1018:11)
    at exports._exceptionWithHostPort (util.js:1041:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1086:14)】
---2017-5-6 16:43:57【Error: Connection terminated
    at Connection.<anonymous> (E:\develop\workspaces\develop1.9.1\node_modules\pg\lib\client.js:183:17)
    at Connection.g (events.js:292:16)
    at emitNone (events.js:86:13)
    at Connection.emit (events.js:185:7)
    at Socket.<anonymous> (E:\develop\workspaces\develop1.9.1\node_modules\pg\lib\connection.js:66:10)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at TCP._handle.close [as _onclose] (net.js:497:12)】
---2017-5-6 16:43:57【Error: Connection terminated
    at Connection.<anonymous> (E:\develop\workspaces\develop1.9.1\node_modules\pg\lib\client.js:183:17)
    at Connection.g (events.js:292:16)
    at emitNone (events.js:86:13)
    at Connection.emit (events.js:185:7)
    at Socket.<anonymous> (E:\develop\workspaces\develop1.9.1\node_modules\pg\lib\connection.js:66:10)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at TCP._handle.close [as _onclose] (net.js:497:12)】
---2017-5-6 16:47:49【Error: Can't set headers after they are sent.
    at ServerResponse.OutgoingMessage.setHeader (_http_outgoing.js:357:11)
    at ServerResponse.header (E:\develop\workspaces\develop1.9.1\node_modules\express\lib\response.js:725:10)
    at ServerResponse.send (E:\develop\workspaces\develop1.9.1\node_modules\express\lib\response.js:170:12)
    at ServerResponse.json (E:\develop\workspaces\develop1.9.1\node_modules\express\lib\response.js:256:15)
    at ServerResponse.send (E:\develop\workspaces\develop1.9.1\node_modules\express\lib\response.js:158:21)
    at E:\develop\workspaces\develop1.9.1\apimain.js:365:10
    at FSReqWrap.oncomplete (fs.js:123:15)】
---2017-5-6 16:48:21【Error: Can't set headers after they are sent.
    at ServerResponse.OutgoingMessage.setHeader (_http_outgoing.js:357:11)
    at ServerResponse.header (E:\develop\workspaces\develop1.9.1\node_modules\express\lib\response.js:725:10)
    at ServerResponse.send (E:\develop\workspaces\develop1.9.1\node_modules\express\lib\response.js:170:12)
    at ServerResponse.json (E:\develop\workspaces\develop1.9.1\node_modules\express\lib\response.js:256:15)
    at ServerResponse.send (E:\develop\workspaces\develop1.9.1\node_modules\express\lib\response.js:158:21)
    at E:\develop\workspaces\develop1.9.1\apimain.js:365:10
    at FSReqWrap.oncomplete (fs.js:123:15)】
---2017-5-6 16:48:21【Error: Can't set headers after they are sent.
    at ServerResponse.OutgoingMessage.setHeader (_http_outgoing.js:357:11)
    at ServerResponse.header (E:\develop\workspaces\develop1.9.1\node_modules\express\lib\response.js:725:10)
    at ServerResponse.send (E:\develop\workspaces\develop1.9.1\node_modules\express\lib\response.js:170:12)
    at ServerResponse.json (E:\develop\workspaces\develop1.9.1\node_modules\express\lib\response.js:256:15)
    at ServerResponse.send (E:\develop\workspaces\develop1.9.1\node_modules\express\lib\response.js:158:21)
    at E:\develop\workspaces\develop1.9.1\apimain.js:365:10
    at FSReqWrap.oncomplete (fs.js:123:15)】
---2017-5-6 16:48:31【Error: Can't set headers after they are sent.
    at ServerResponse.OutgoingMessage.setHeader (_http_outgoing.js:357:11)
    at ServerResponse.header (E:\develop\workspaces\develop1.9.1\node_modules\express\lib\response.js:725:10)
    at ServerResponse.send (E:\develop\workspaces\develop1.9.1\node_modules\express\lib\response.js:170:12)
    at ServerResponse.json (E:\develop\workspaces\develop1.9.1\node_modules\express\lib\response.js:256:15)
    at ServerResponse.send (E:\develop\workspaces\develop1.9.1\node_modules\express\lib\response.js:158:21)
    at E:\develop\workspaces\develop1.9.1\apimain.js:365:10
    at FSReqWrap.oncomplete (fs.js:123:15)】
---2017-5-6 16:48:31【Error: Can't set headers after they are sent.
    at ServerResponse.OutgoingMessage.setHeader (_http_outgoing.js:357:11)
    at ServerResponse.header (E:\develop\workspaces\develop1.9.1\node_modules\express\lib\response.js:725:10)
    at ServerResponse.send (E:\develop\workspaces\develop1.9.1\node_modules\express\lib\response.js:170:12)
    at ServerResponse.json (E:\develop\workspaces\develop1.9.1\node_modules\express\lib\response.js:256:15)
    at ServerResponse.send (E:\develop\workspaces\develop1.9.1\node_modules\express\lib\response.js:158:21)
    at E:\develop\workspaces\develop1.9.1\apimain.js:365:10
    at FSReqWrap.oncomplete (fs.js:123:15)】
---2017-5-6 16:48:31【Error: Can't set headers after they are sent.
    at ServerResponse.OutgoingMessage.setHeader (_http_outgoing.js:357:11)
    at ServerResponse.header (E:\develop\workspaces\develop1.9.1\node_modules\express\lib\response.js:725:10)
    at ServerResponse.send (E:\develop\workspaces\develop1.9.1\node_modules\express\lib\response.js:170:12)
    at ServerResponse.json (E:\develop\workspaces\develop1.9.1\node_modules\express\lib\response.js:256:15)
    at ServerResponse.send (E:\develop\workspaces\develop1.9.1\node_modules\express\lib\response.js:158:21)
    at E:\develop\workspaces\develop1.9.1\apimain.js:365:10
    at FSReqWrap.oncomplete (fs.js:123:15)】
---2017-5-6 16:52:55【error: terminating connection due to administrator command
    at Connection.parseE (E:\develop\workspaces\develop1.9.1\node_modules\pg\lib\connection.js:539:11)
    at Connection.parseMessage (E:\develop\workspaces\develop1.9.1\node_modules\pg\lib\connection.js:366:17)
    at Socket.<anonymous> (E:\develop\workspaces\develop1.9.1\node_modules\pg\lib\connection.js:105:22)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
    at TCP.onread (net.js:547:20)】
---2017-5-6 16:52:55【Error: read ECONNRESET
    at exports._errnoException (util.js:1018:11)
    at TCP.onread (net.js:568:26)】
---2017-5-6 16:52:55【Error: read ECONNRESET
    at exports._errnoException (util.js:1018:11)
    at TCP.onread (net.js:568:26)】
---2017-5-6 16:52:55【Error: read ECONNRESET
    at exports._errnoException (util.js:1018:11)
    at TCP.onread (net.js:568:26)】
---2017-5-6 16:52:55【error: terminating connection due to administrator command
    at Connection.parseE (E:\develop\workspaces\develop1.9.1\node_modules\pg\lib\connection.js:539:11)
    at Connection.parseMessage (E:\develop\workspaces\develop1.9.1\node_modules\pg\lib\connection.js:366:17)
    at Socket.<anonymous> (E:\develop\workspaces\develop1.9.1\node_modules\pg\lib\connection.js:105:22)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
    at TCP.onread (net.js:547:20)】
---2017-5-6 16:52:55【Error: read ECONNRESET
    at exports._errnoException (util.js:1018:11)
    at TCP.onread (net.js:568:26)】
---2017-5-6 16:52:55【error: terminating connection due to administrator command
    at Connection.parseE (E:\develop\workspaces\develop1.9.1\node_modules\pg\lib\connection.js:539:11)
    at Connection.parseMessage (E:\develop\workspaces\develop1.9.1\node_modules\pg\lib\connection.js:366:17)
    at Socket.<anonymous> (E:\develop\workspaces\develop1.9.1\node_modules\pg\lib\connection.js:105:22)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
    at TCP.onread (net.js:547:20)】
---2017-5-6 16:52:55【Error: read ECONNRESET
    at exports._errnoException (util.js:1018:11)
    at TCP.onread (net.js:568:26)】
---2017-5-6 16:52:55【error: terminating connection due to administrator command
    at Connection.parseE (E:\develop\workspaces\develop1.9.1\node_modules\pg\lib\connection.js:539:11)
    at Connection.parseMessage (E:\develop\workspaces\develop1.9.1\node_modules\pg\lib\connection.js:366:17)
    at Socket.<anonymous> (E:\develop\workspaces\develop1.9.1\node_modules\pg\lib\connection.js:105:22)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
    at TCP.onread (net.js:547:20)】
---2017-5-6 16:52:55【Error: read ECONNRESET
    at exports._errnoException (util.js:1018:11)
    at TCP.onread (net.js:568:26)】
---2017-5-6 16:52:56【error: terminating connection due to administrator command
    at Connection.parseE (E:\develop\workspaces\develop1.9.1\node_modules\pg\lib\connection.js:539:11)
    at Connection.parseMessage (E:\develop\workspaces\develop1.9.1\node_modules\pg\lib\connection.js:366:17)
    at Socket.<anonymous> (E:\develop\workspaces\develop1.9.1\node_modules\pg\lib\connection.js:105:22)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
    at TCP.onread (net.js:547:20)】
---2017-5-6 16:52:56【Error: read ECONNRESET
    at exports._errnoException (util.js:1018:11)
    at TCP.onread (net.js:568:26)】
---2017-5-6 16:52:56【error: terminating connection due to administrator command
    at Connection.parseE (E:\develop\workspaces\develop1.9.1\node_modules\pg\lib\connection.js:539:11)
    at Connection.parseMessage (E:\develop\workspaces\develop1.9.1\node_modules\pg\lib\connection.js:366:17)
    at Socket.<anonymous> (E:\develop\workspaces\develop1.9.1\node_modules\pg\lib\connection.js:105:22)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
    at TCP.onread (net.js:547:20)】
---2017-5-6 16:52:56【Error: read ECONNRESET
    at exports._errnoException (util.js:1018:11)
    at TCP.onread (net.js:568:26)】
---2017-5-6 16:52:56【error: terminating connection due to administrator command
    at Connection.parseE (E:\develop\workspaces\develop1.9.1\node_modules\pg\lib\connection.js:539:11)
    at Connection.parseMessage (E:\develop\workspaces\develop1.9.1\node_modules\pg\lib\connection.js:366:17)
    at Socket.<anonymous> (E:\develop\workspaces\develop1.9.1\node_modules\pg\lib\connection.js:105:22)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
    at TCP.onread (net.js:547:20)】
---2017-5-6 16:52:56【Error: read ECONNRESET
    at exports._errnoException (util.js:1018:11)
    at TCP.onread (net.js:568:26)】
---2017-5-6 16:52:56【error: terminating connection due to administrator command
    at Connection.parseE (E:\develop\workspaces\develop1.9.1\node_modules\pg\lib\connection.js:539:11)
    at Connection.parseMessage (E:\develop\workspaces\develop1.9.1\node_modules\pg\lib\connection.js:366:17)
    at Socket.<anonymous> (E:\develop\workspaces\develop1.9.1\node_modules\pg\lib\connection.js:105:22)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
    at TCP.onread (net.js:547:20)】
---2017-5-6 16:52:56【Error: read ECONNRESET
    at exports._errnoException (util.js:1018:11)
    at TCP.onread (net.js:568:26)】
---2017-5-6 16:53:45【错误:连接PG数据库失败,错误信息:Error: connect ETIMEDOUT 192.168.0.100:5432】
---2017-5-6 16:53:45【Error: connect ETIMEDOUT 192.168.0.100:5432
    at Object.exports._errnoException (util.js:1018:11)
    at exports._exceptionWithHostPort (util.js:1041:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1086:14)】
---2017-5-6 16:53:45【错误:连接PG数据库失败,错误信息:Error: connect ETIMEDOUT 192.168.0.100:5432】
---2017-5-6 16:53:45【Error: connect ETIMEDOUT 192.168.0.100:5432
    at Object.exports._errnoException (util.js:1018:11)
    at exports._exceptionWithHostPort (util.js:1041:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1086:14)】
---2017-5-6 16:53:45【错误:连接PG数据库失败,错误信息:Error: connect ETIMEDOUT 192.168.0.100:5432】
---2017-5-6 16:53:45【Error: connect ETIMEDOUT 192.168.0.100:5432
    at Object.exports._errnoException (util.js:1018:11)
    at exports._exceptionWithHostPort (util.js:1041:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1086:14)】
---2017-5-6 16:53:45【错误:连接PG数据库失败,错误信息:Error: connect ETIMEDOUT 192.168.0.100:5432】
---2017-5-6 16:53:45【Error: connect ETIMEDOUT 192.168.0.100:5432
    at Object.exports._errnoException (util.js:1018:11)
    at exports._exceptionWithHostPort (util.js:1041:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1086:14)】
---2017-5-6 16:53:45【Error: connect ETIMEDOUT 192.168.0.100:5432
    at Object.exports._errnoException (util.js:1018:11)
    at exports._exceptionWithHostPort (util.js:1041:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1086:14)】
---2017-5-6 16:53:45【Error: connect ETIMEDOUT 192.168.0.100:5432
    at Object.exports._errnoException (util.js:1018:11)
    at exports._exceptionWithHostPort (util.js:1041:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1086:14)】
---2017-5-6 16:53:45【Error: connect ETIMEDOUT 192.168.0.100:5432
    at Object.exports._errnoException (util.js:1018:11)
    at exports._exceptionWithHostPort (util.js:1041:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1086:14)】
---2017-5-6 16:53:45【Error: connect ETIMEDOUT 192.168.0.100:5432
    at Object.exports._errnoException (util.js:1018:11)
    at exports._exceptionWithHostPort (util.js:1041:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1086:14)】
---2017-5-6 16:53:45【Error: Connection terminated
    at Connection.<anonymous> (E:\develop\workspaces\develop1.9.1\node_modules\pg\lib\client.js:183:17)
    at Connection.g (events.js:292:16)
    at emitNone (events.js:86:13)
    at Connection.emit (events.js:185:7)
    at Socket.<anonymous> (E:\develop\workspaces\develop1.9.1\node_modules\pg\lib\connection.js:66:10)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at TCP._handle.close [as _onclose] (net.js:497:12)】
---2017-5-6 16:53:45【Error: Connection terminated
    at Connection.<anonymous> (E:\develop\workspaces\develop1.9.1\node_modules\pg\lib\client.js:183:17)
    at Connection.g (events.js:292:16)
    at emitNone (events.js:86:13)
    at Connection.emit (events.js:185:7)
    at Socket.<anonymous> (E:\develop\workspaces\develop1.9.1\node_modules\pg\lib\connection.js:66:10)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at TCP._handle.close [as _onclose] (net.js:497:12)】
---2017-5-6 16:53:45【Error: Connection terminated
    at Connection.<anonymous> (E:\develop\workspaces\develop1.9.1\node_modules\pg\lib\client.js:183:17)
    at Connection.g (events.js:292:16)
    at emitNone (events.js:86:13)
    at Connection.emit (events.js:185:7)
    at Socket.<anonymous> (E:\develop\workspaces\develop1.9.1\node_modules\pg\lib\connection.js:66:10)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at TCP._handle.close [as _onclose] (net.js:497:12)】
---2017-5-6 16:53:45【Error: Connection terminated
    at Connection.<anonymous> (E:\develop\workspaces\develop1.9.1\node_modules\pg\lib\client.js:183:17)
    at Connection.g (events.js:292:16)
    at emitNone (events.js:86:13)
    at Connection.emit (events.js:185:7)
    at Socket.<anonymous> (E:\develop\workspaces\develop1.9.1\node_modules\pg\lib\connection.js:66:10)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at TCP._handle.close [as _onclose] (net.js:497:12)】
---2017-5-6 16:53:45【Error: Connection terminated
    at Connection.<anonymous> (E:\develop\workspaces\develop1.9.1\node_modules\pg\lib\client.js:183:17)
    at Connection.g (events.js:292:16)
    at emitNone (events.js:86:13)
    at Connection.emit (events.js:185:7)
    at Socket.<anonymous> (E:\develop\workspaces\develop1.9.1\node_modules\pg\lib\connection.js:66:10)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at TCP._handle.close [as _onclose] (net.js:497:12)】
---2017-5-6 16:53:45【Error: Connection terminated
    at Connection.<anonymous> (E:\develop\workspaces\develop1.9.1\node_modules\pg\lib\client.js:183:17)
    at Connection.g (events.js:292:16)
    at emitNone (events.js:86:13)
    at Connection.emit (events.js:185:7)
    at Socket.<anonymous> (E:\develop\workspaces\develop1.9.1\node_modules\pg\lib\connection.js:66:10)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at TCP._handle.close [as _onclose] (net.js:497:12)】
---2017-5-6 16:53:45【Error: Connection terminated
    at Connection.<anonymous> (E:\develop\workspaces\develop1.9.1\node_modules\pg\lib\client.js:183:17)
    at Connection.g (events.js:292:16)
    at emitNone (events.js:86:13)
    at Connection.emit (events.js:185:7)
    at Socket.<anonymous> (E:\develop\workspaces\develop1.9.1\node_modules\pg\lib\connection.js:66:10)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at TCP._handle.close [as _onclose] (net.js:497:12)】
---2017-5-6 16:53:45【Error: Connection terminated
    at Connection.<anonymous> (E:\develop\workspaces\develop1.9.1\node_modules\pg\lib\client.js:183:17)
    at Connection.g (events.js:292:16)
    at emitNone (events.js:86:13)
    at Connection.emit (events.js:185:7)
    at Socket.<anonymous> (E:\develop\workspaces\develop1.9.1\node_modules\pg\lib\connection.js:66:10)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at TCP._handle.close [as _onclose] (net.js:497:12)】
---2017-5-6 16:53:45【Error: connect ETIMEDOUT 192.168.0.100:5432
    at Object.exports._errnoException (util.js:1018:11)
    at exports._exceptionWithHostPort (util.js:1041:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1086:14)】
---2017-5-6 16:53:45【Error: connect ETIMEDOUT 192.168.0.100:5432
    at Object.exports._errnoException (util.js:1018:11)
    at exports._exceptionWithHostPort (util.js:1041:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1086:14)】
---2017-5-6 16:53:45【Error: connect ETIMEDOUT 192.168.0.100:5432
    at Object.exports._errnoException (util.js:1018:11)
    at exports._exceptionWithHostPort (util.js:1041:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1086:14)】
---2017-5-6 16:53:45【Error: Connection terminated
    at Connection.<anonymous> (E:\develop\workspaces\develop1.9.1\node_modules\pg\lib\client.js:183:17)
    at Connection.g (events.js:292:16)
    at emitNone (events.js:86:13)
    at Connection.emit (events.js:185:7)
    at Socket.<anonymous> (E:\develop\workspaces\develop1.9.1\node_modules\pg\lib\connection.js:66:10)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at TCP._handle.close [as _onclose] (net.js:497:12)】
---2017-5-6 16:53:45【Error: Connection terminated
    at Connection.<anonymous> (E:\develop\workspaces\develop1.9.1\node_modules\pg\lib\client.js:183:17)
    at Connection.g (events.js:292:16)
    at emitNone (events.js:86:13)
    at Connection.emit (events.js:185:7)
    at Socket.<anonymous> (E:\develop\workspaces\develop1.9.1\node_modules\pg\lib\connection.js:66:10)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at TCP._handle.close [as _onclose] (net.js:497:12)】
---2017-5-6 16:53:45【Error: Connection terminated
    at Connection.<anonymous> (E:\develop\workspaces\develop1.9.1\node_modules\pg\lib\client.js:183:17)
    at Connection.g (events.js:292:16)
    at emitNone (events.js:86:13)
    at Connection.emit (events.js:185:7)
    at Socket.<anonymous> (E:\develop\workspaces\develop1.9.1\node_modules\pg\lib\connection.js:66:10)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at TCP._handle.close [as _onclose] (net.js:497:12)】
---2017-5-6 16:53:47【Error: connect ETIMEDOUT 192.168.0.100:5432
    at Object.exports._errnoException (util.js:1018:11)
    at exports._exceptionWithHostPort (util.js:1041:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1086:14)】
---2017-5-6 16:53:47【Error: Connection terminated
    at Connection.<anonymous> (E:\develop\workspaces\develop1.9.1\node_modules\pg\lib\client.js:183:17)
    at Connection.g (events.js:292:16)
    at emitNone (events.js:86:13)
    at Connection.emit (events.js:185:7)
    at Socket.<anonymous> (E:\develop\workspaces\develop1.9.1\node_modules\pg\lib\connection.js:66:10)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at TCP._handle.close [as _onclose] (net.js:497:12)】
---2017-5-6 16:53:48【Error: connect ETIMEDOUT 192.168.0.100:5432
    at Object.exports._errnoException (util.js:1018:11)
    at exports._exceptionWithHostPort (util.js:1041:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1086:14)】
---2017-5-6 16:53:48【Error: Connection terminated
    at Connection.<anonymous> (E:\develop\workspaces\develop1.9.1\node_modules\pg\lib\client.js:183:17)
    at Connection.g (events.js:292:16)
    at emitNone (events.js:86:13)
    at Connection.emit (events.js:185:7)
    at Socket.<anonymous> (E:\develop\workspaces\develop1.9.1\node_modules\pg\lib\connection.js:66:10)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at TCP._handle.close [as _onclose] (net.js:497:12)】
---2017-5-6 16:54:13【错误:连接PG数据库失败,错误信息:Error: connect ETIMEDOUT 192.168.0.100:5432】
---2017-5-6 16:54:13【Error: connect ETIMEDOUT 192.168.0.100:5432
    at Object.exports._errnoException (util.js:1018:11)
    at exports._exceptionWithHostPort (util.js:1041:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1086:14)】
---2017-5-6 16:54:13【Error: Connection terminated
    at Connection.<anonymous> (E:\develop\workspaces\develop1.9.1\node_modules\pg\lib\client.js:183:17)
    at Connection.g (events.js:292:16)
    at emitNone (events.js:86:13)
    at Connection.emit (events.js:185:7)
    at Socket.<anonymous> (E:\develop\workspaces\develop1.9.1\node_modules\pg\lib\connection.js:66:10)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at TCP._handle.close [as _onclose] (net.js:497:12)】
---2017-5-6 16:54:13【Error: connect ETIMEDOUT 192.168.0.100:5432
    at Object.exports._errnoException (util.js:1018:11)
    at exports._exceptionWithHostPort (util.js:1041:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1086:14)】
---2017-5-6 16:54:13【Error: connect ETIMEDOUT 192.168.0.100:5432
    at Object.exports._errnoException (util.js:1018:11)
    at exports._exceptionWithHostPort (util.js:1041:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1086:14)】
---2017-5-6 16:54:13【Error: connect ETIMEDOUT 192.168.0.100:5432
    at Object.exports._errnoException (util.js:1018:11)
    at exports._exceptionWithHostPort (util.js:1041:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1086:14)】
---2017-5-6 16:54:13【Error: connect ETIMEDOUT 192.168.0.100:5432
    at Object.exports._errnoException (util.js:1018:11)
    at exports._exceptionWithHostPort (util.js:1041:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1086:14)】
---2017-5-6 16:54:13【Error: connect ETIMEDOUT 192.168.0.100:5432
    at Object.exports._errnoException (util.js:1018:11)
    at exports._exceptionWithHostPort (util.js:1041:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1086:14)】
---2017-5-6 16:54:13【Error: connect ETIMEDOUT 192.168.0.100:5432
    at Object.exports._errnoException (util.js:1018:11)
    at exports._exceptionWithHostPort (util.js:1041:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1086:14)】
---2017-5-6 16:54:13【Error: connect ETIMEDOUT 192.168.0.100:5432
    at Object.exports._errnoException (util.js:1018:11)
    at exports._exceptionWithHostPort (util.js:1041:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1086:14)】
---2017-5-6 16:54:13【Error: connect ETIMEDOUT 192.168.0.100:5432
    at Object.exports._errnoException (util.js:1018:11)
    at exports._exceptionWithHostPort (util.js:1041:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1086:14)】
---2017-5-6 16:54:13【Error: connect ETIMEDOUT 192.168.0.100:5432
    at Object.exports._errnoException (util.js:1018:11)
    at exports._exceptionWithHostPort (util.js:1041:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1086:14)】
---2017-5-6 16:54:13【Error: connect ETIMEDOUT 192.168.0.100:5432
    at Object.exports._errnoException (util.js:1018:11)
    at exports._exceptionWithHostPort (util.js:1041:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1086:14)】
---2017-5-6 16:54:13【Error: Connection terminated
    at Connection.<anonymous> (E:\develop\workspaces\develop1.9.1\node_modules\pg\lib\client.js:183:17)
    at Connection.g (events.js:292:16)
    at emitNone (events.js:86:13)
    at Connection.emit (events.js:185:7)
    at Socket.<anonymous> (E:\develop\workspaces\develop1.9.1\node_modules\pg\lib\connection.js:66:10)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at TCP._handle.close [as _onclose] (net.js:497:12)】
---2017-5-6 16:54:13【Error: Connection terminated
    at Connection.<anonymous> (E:\develop\workspaces\develop1.9.1\node_modules\pg\lib\client.js:183:17)
    at Connection.g (events.js:292:16)
    at emitNone (events.js:86:13)
    at Connection.emit (events.js:185:7)
    at Socket.<anonymous> (E:\develop\workspaces\develop1.9.1\node_modules\pg\lib\connection.js:66:10)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at TCP._handle.close [as _onclose] (net.js:497:12)】
---2017-5-6 16:54:13【Error: Connection terminated
    at Connection.<anonymous> (E:\develop\workspaces\develop1.9.1\node_modules\pg\lib\client.js:183:17)
    at Connection.g (events.js:292:16)
    at emitNone (events.js:86:13)
    at Connection.emit (events.js:185:7)
    at Socket.<anonymous> (E:\develop\workspaces\develop1.9.1\node_modules\pg\lib\connection.js:66:10)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at TCP._handle.close [as _onclose] (net.js:497:12)】
---2017-5-6 16:54:13【Error: Connection terminated
    at Connection.<anonymous> (E:\develop\workspaces\develop1.9.1\node_modules\pg\lib\client.js:183:17)
    at Connection.g (events.js:292:16)
    at emitNone (events.js:86:13)
    at Connection.emit (events.js:185:7)
    at Socket.<anonymous> (E:\develop\workspaces\develop1.9.1\node_modules\pg\lib\connection.js:66:10)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at TCP._handle.close [as _onclose] (net.js:497:12)】
---2017-5-6 16:54:13【Error: Connection terminated
    at Connection.<anonymous> (E:\develop\workspaces\develop1.9.1\node_modules\pg\lib\client.js:183:17)
    at Connection.g (events.js:292:16)
    at emitNone (events.js:86:13)
    at Connection.emit (events.js:185:7)
    at Socket.<anonymous> (E:\develop\workspaces\develop1.9.1\node_modules\pg\lib\connection.js:66:10)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at TCP._handle.close [as _onclose] (net.js:497:12)】
---2017-5-6 16:54:13【Error: Connection terminated
    at Connection.<anonymous> (E:\develop\workspaces\develop1.9.1\node_modules\pg\lib\client.js:183:17)
    at Connection.g (events.js:292:16)
    at emitNone (events.js:86:13)
    at Connection.emit (events.js:185:7)
    at Socket.<anonymous> (E:\develop\workspaces\develop1.9.1\node_modules\pg\lib\connection.js:66:10)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at TCP._handle.close [as _onclose] (net.js:497:12)】
---2017-5-6 16:54:13【Error: Connection terminated
    at Connection.<anonymous> (E:\develop\workspaces\develop1.9.1\node_modules\pg\lib\client.js:183:17)
    at Connection.g (events.js:292:16)
    at emitNone (events.js:86:13)
    at Connection.emit (events.js:185:7)
    at Socket.<anonymous> (E:\develop\workspaces\develop1.9.1\node_modules\pg\lib\connection.js:66:10)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at TCP._handle.close [as _onclose] (net.js:497:12)】
---2017-5-6 16:54:13【Error: Connection terminated
    at Connection.<anonymous> (E:\develop\workspaces\develop1.9.1\node_modules\pg\lib\client.js:183:17)
    at Connection.g (events.js:292:16)
    at emitNone (events.js:86:13)
    at Connection.emit (events.js:185:7)
    at Socket.<anonymous> (E:\develop\workspaces\develop1.9.1\node_modules\pg\lib\connection.js:66:10)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at TCP._handle.close [as _onclose] (net.js:497:12)】
---2017-5-6 16:54:13【Error: Connection terminated
    at Connection.<anonymous> (E:\develop\workspaces\develop1.9.1\node_modules\pg\lib\client.js:183:17)
    at Connection.g (events.js:292:16)
    at emitNone (events.js:86:13)
    at Connection.emit (events.js:185:7)
    at Socket.<anonymous> (E:\develop\workspaces\develop1.9.1\node_modules\pg\lib\connection.js:66:10)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at TCP._handle.close [as _onclose] (net.js:497:12)】
---2017-5-6 16:54:13【Error: Connection terminated
    at Connection.<anonymous> (E:\develop\workspaces\develop1.9.1\node_modules\pg\lib\client.js:183:17)
    at Connection.g (events.js:292:16)
    at emitNone (events.js:86:13)
    at Connection.emit (events.js:185:7)
    at Socket.<anonymous> (E:\develop\workspaces\develop1.9.1\node_modules\pg\lib\connection.js:66:10)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at TCP._handle.close [as _onclose] (net.js:497:12)】
